NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/preset/Preset.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/PresetInfoDialog.java
NonMaps/src/war/NonMaps.css

+ moved Bank info up
+ changed format of bankinfo (NUMBER - NAME)
+ moved position in name row
+ added String getPaddedNumber() in preset. format (001-999)

presetinfo minor changes

---

playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankEditButtonMenu.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankEditButtonMenu.h

works as intendet but i removed wrong impl of time callback to rebuild the menu all the time

removed timer to rebuild bank menu and formatted

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/ServerProxy.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/PresetManager.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/CompareDialog.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetContextMenu.java
playground/src/presets/PresetManagerActions.cpp

Standard preset context menu allows comparison to Editbuffer

added comparison of preset - editbuffer

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Bank.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Tape.java

makes docking indication smaller and removes it from currentDragTarget

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/PresetInfoDialog.java
NonMaps/src/war/NonMaps.css

added buttons that change the tags as you would expect

finished color tags in preset info

---

playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp

installed button repetition for B&C in presetManagerLayout

---

playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetInfoContent.cpp
playground/src/proxies/hwui/panel-unit/boled/setup/DateTimeEditor.cpp

Fix time formats

---

playground/src/proxies/hwui/panel-unit/boled/parameter-screens/InfoLayout.cpp

experimental untested on device

doubled the scrolling value in all info screens

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Bank.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/preset/Preset.java

Multi selection on preset that is included in the selection is now forbidden

Fix misc mul sel fixes

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/Belt.java

this prevents the preset to go through to presetmanager and wont create a new bank now

made belt respond to dragged preset

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/CompareDialog.java

Implemented the correct behaviour:  closing multiple selection if compare is opened

Feature end multiple selection if all compare windows are closed

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BankControl.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/EmptyBeltPreset.java

added empty preset label in belt and "BOLED" style preset selection rectangle in belt aswell

added preset selection rectangle in preset belt tab

---

playground/src/presets/PresetManager.cpp
playground/src/presets/PresetManager.h

#proud did what henry was asking for

Feature change bank pos should change all numbers in bethween

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/ServerProxy.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/preset/ColorTag.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/CompareDialog.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/PresetInfoDialog.java
NonMaps/src/war/NonMaps.css
playground/src/presets/BankActions.cpp

moved colour line in info
changed css to be more centred horizontal
changed highlight
added automatic attribute setting for colour if not present (server proxy now has "setPresetAttributeHidden", that starts cuckoo transaction)

Misc changes at the colour tagging feature 

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Bank.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Tape.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/preset/Preset.java

reduced width for name in preset list so that the .. will not leave the area anymore

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/MultiplePresetSelection.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/PresetManager.java

Feature multiple preset selection up down selection

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/Rect.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/MoveSomeBanksLayer.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/PresetManager.java

the multiple preset selection rectangle is now trying too hard to be cool, almost to a point where it's cringe worthy.

changed mul sel rectangle to edgy and removed padding

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/BankInfoDialog.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/PresetInfoDialog.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/BeltButton.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/ContextMenuButton.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BankControl.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BankControlArea.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BankHeader.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BankTitle.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BeltPreset.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BeltPresetLayout.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetColorTag.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetList.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/StoreOptionsMenu.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/menu/GlobalMenu.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/menu/MenuHeader.java

Various fixes and enhancements

"Feature make belt great again" again

---

playground/src/proxies/hwui/panel-unit/boled/InfoContent.cpp
playground/src/proxies/hwui/panel-unit/boled/InfoContent.h
playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankInfoCaption.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankInfoContent.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetInfoContent.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetInfoContent.h

Fixes: "*BOLED: Bank Info: Die Einträge für Name und Comment sind um ca. 2 Pixel nach oben verrutscht.*" and "BOLED: Bank Info: oben links nicht den Namen sondern die Nummer der Bank (zentriert) einblenden"
Improves Codequality by using the InfoField structure instead of manualy adding and taking care of Controls

Changed InfoContent Class for Code Quality

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/Control.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/preset/Preset.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/DragProxy.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BeltPreset.java

added Control setting that allows for dragging on itself or not. Overwritten by BeltPreset to fix a bug

Fix - Preset Drag on Itself also remove Insert Lines in Banks for unnecessary options

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/parameters/LabelModuleHeader.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/parameters/ParameterEditor.java
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterEditButtonMenu.cpp

added stuff, that only allows lock all if at least one group is unlocked

Lock WebUI and BOLED rule change

---

playground/src/presets/PresetBank.cpp

changed from untitled preset bank to untitled bank

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Tape.java

added check if dragged control is bank or not to disable the insert tape

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/GlobalButtons.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/BeltButton.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/IActivatable.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/SoundBeltButton.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/sound/BeltSoundLayout.java

moved lock symbol into tab button

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/CurrentPresetNumber.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterL.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterM.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterXL.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterXXL.java

cloned the layout postfix from xxl to xl, l and m

---

playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp
playground/src/proxies/hwui/panel-unit/boled/undo/UndoIndicator.cpp

fixes #248 
sorry about the commits, f'd the merge up again

Feature 248

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/StorePreset.java

refactored StorePreset Overwrite branch and prevent using nullpeter

---

playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ScaleParameterLayout.cpp

only displays reset when parameter is changed now

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/PresetInfoDialog.java
NonMaps/src/war/NonMaps.css

fixes #221

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/PresetManager.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BankContextMenu.java

added simple algorithm for calculating bank position

---

NonMaps/src/war/NonMaps.css

fixed svg to not have a filled background

---

playground/src/groups/SVFilterGroup.cpp

S.V. -> SV

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/Belt.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/ParameterContextMenu.java

conditionally add the menu entry, show the belt, if necessary

---

playground/src/proxies/hwui/panel-unit/PanelUnitParameterEditMode.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterNameLabel.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterNameLabel.h

subscribed parameterNameLabel to presetloaded signal

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/PresetManager.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetContextMenu.java

added deleter for banks if empty modal dialog

---

playground/src/parameters/ModulateableParameter.cpp
playground/src/parameters/ModulateableParameter.h
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/LowerModulationBoundControl.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SelectedParameterModAmount.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/UpperModulationBoundControl.cpp

fix clipped mod range

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/TextCropper.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Header.java
playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetNameLabel.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetNameLabel.h

added text cropper back in, wherever that went?!

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/InfoDialog/PresetInfoWidget.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/PresetInfoDialog.java

added force override flag in update preset info

---

playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp

moved undo

---

playground/src/proxies/hwui/base-unit/soled/PresetsLayout.cpp
playground/src/proxies/hwui/base-unit/soled/PresetsLayout.h

subscribed presetslayout to presetloaded

---

playground/src/proxies/hwui/base-unit/soled/PresetsLayout.cpp

fixed #331

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/preset/Preset.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetDeleter.java

added preset color selection if in modal deleter-dialog

---

playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ModulationBoundLabel.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ModulationBoundLabel.h

added suffix color for fine in mc carousell

---

playground/src/proxies/hwui/base-unit/soled/BanksLayout.cpp
playground/src/proxies/hwui/base-unit/soled/BanksLayout.h

added bank changed connection + refactor

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/ServerProxy.java
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.h
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/StaticKnubbelSlider.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/StaticKnubbelSlider.h

made better recall layout

---

playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp

flipped positions of old value and recall value

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/sound/BeltSoundLayout.java

removed Morph from webui belt, as it does not have a function yet

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterL.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterM.java

added margin twice

---

NonMaps/src/war/NonMaps.css

css changes for preset info dialog

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/BankInfoDialog.java
NonMaps/src/war/NonMaps.css

fixed css class assignment

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/parameters/ModulationSourceHighPriority.java

limit size of mod sources

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Tape.java

fixed preset dragging

---

playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableParameterLayouts.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableParameterLayouts.h
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/CurrentModulatedValueLabel.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/CurrentModulatedValueLabel.h
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/Defaultable.h
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/LowerModulationBoundControl.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/LowerModulationBoundControl.h
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ModulationCarousel.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ModulationCarousel.h
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/UpperModulationBoundControl.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/UpperModulationBoundControl.h

default for mod limits and mod amt

---

playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetEditButtonMenu.cpp

changed default option in preset edit button menu to rename

---

playground/src/parameters/ModulateableParameter.cpp

changed mc ammounts in diff to -100..100 and added %

---

playground/src/presets/BankActions.cpp
playground/src/presets/BankChangeBlocker.cpp
playground/src/presets/BankChangeBlocker.h
playground/src/presets/PresetBank.cpp
playground/src/presets/PresetBank.h
playground/src/presets/PresetManager.cpp

added bank change blocker that prevents captured bank from setting m_lastChange in onChange

---

playground/src/presets/EditBuffer.cpp
playground/src/proxies/hwui/panel-unit/PanelUnitPresetMode.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/AppendOverwriteInsertButtonMenu.cpp

throttler has to check if the usage mode ist still the active one

---

NonMaps/src/war/NonMaps.css

fixed alignment in left column in preset compare dialog

---

playground/src/presets/PresetManagerActions.cpp
playground/src/proxies/hwui/panel-unit/boled/setup/ImportBackupEditor.cpp

added explicit send to LPC after Restore

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/NonMapsWheelHandler.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/BeltParameterLayout.java

added shift modifier-or to wheel belt parameter

---

playground/src/presets/PresetBank.cpp
playground/src/presets/PresetManagerActions.cpp

changed bank rename to not select bank afterwards

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/SearchQueryDialog.java
NonMaps/src/war/NonMaps.css

changed css and change spelling of matches to Matches and removed .

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/LoadButtonArea.java

changed width of BankInfoBox again

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/PresetManager.java

fixed prev next preset buttons, by looking at the selected preset rather than the loaded one
#490

Preset Selection Buttons

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BankTitle.java

resized bank header font to 85% of original size

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/BeltParameterLayout.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/MCRadioButton.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/UpperLowerBoundListener.java

Fix webui clipping

---

playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ModulationCarousel.cpp

moved upper limit down by one pixel

---

playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/EditBufferInfoContent.cpp

removed uiversion and lastchange from eb info

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/SearchQueryDialog.java
NonMaps/src/war/NonMaps.css

changed css to be more straigthforward, and also work in edge :|

---

playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp

Remove Artifact Lock + PresetLayout - > Edit

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/BeltParameterLayout.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/UpperLowerBoundListener.java

changed quantization of Upper/Lower Bound to 1000 to allow for fine

---

playground/src/proxies/hwui/controls/Label.h

fixed encoded compare

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/NonMapsWheelHandler.java

changed mouse wheel to use shift as fine modifier

---

playground/src/device-settings/DebugLevel.h
playground/src/playground.h

debuglevel enums now printing properly again

---

playground/resources/ParameterList.csv
playground/src/parameters/ModulateableParameter.cpp
playground/src/parameters/Parameter.cpp
playground/src/parameters/PedalParameter.cpp
playground/src/parameters/RibbonParameter.cpp

replaced ParameterList with new latest version from the drive

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/html/presetSearch/PresetSearch.java

added select all text and set focus init when search dialog is opened

---

playground/src/proxies/hwui/panel-unit/PanelUnitParameterEditMode.cpp

added Flanger Envelope in Active Overview

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/PresetManager.java

added remove not contained presets from multi selection in handle Multi Selection
#584

Fix Preset-Multi-Selection not deselecting not contained presets 

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/PresetManager.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetManagerContextMenu.java

now pm contextmenu changes text when in move all banks

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/PresetManager.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Bank.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BankContextMenu.java

added minimize all and full size all (banks) in bank context menu, default action is minimize all, if any bank is maximized, matter to change?
#579

Minimize / Full Size All

---

playground/src/parameters/RibbonParameter.cpp
playground/src/presets/EditBuffer.cpp
playground/src/proxies/hwui/FourStateLED.cpp
playground/src/proxies/hwui/FourStateLED.h
playground/src/proxies/hwui/base-unit/BaseUnit.cpp
playground/src/proxies/hwui/base-unit/BaseUnit.h
playground/src/proxies/hwui/base-unit/Ribbon.cpp

587 + 572 

---

NonMaps/CMakeLists.txt
NonMaps/MCView/index.html
NonMaps/MCView/js.js
NonMaps/MCView/style.css
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/menu/GlobalMenu.java
playground/src/groups/MacroControlMappingGroup.cpp
playground/src/groups/MacroControlMappingGroup.h
playground/src/http/HTTPServer.cpp
playground/src/presets/EditBuffer.cpp
playground/src/presets/EditBuffer.h
playground/src/presets/EditBufferActions.cpp

Feature mc stable exp

---

NonMaps/src/war/style.css

changed font color for search dialog text

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/html/presetSearch/PresetSearch.java

#630 
Quits Preset Search on Escape

added PresetSearchDialog Close on Escape Press

---

playground/src/proxies/hwui/panel-unit/PanelUnitParameterEditMode.cpp
playground/src/proxies/hwui/panel-unit/PanelUnitParameterEditMode.h
playground/src/proxies/hwui/panel-unit/PanelUnitPresetMode.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.h

adding shift capabilitys that carry over multiple layouts

---

playground/src/parameters/descriptions/111.txt
playground/src/parameters/descriptions/81.txt

#576 - added updated parameter descriptions

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/parameters/CombFilter/CombFilterCol3.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/parameters/KeyTrackParameter.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/parameters/KeyTrkLabelModulationSource.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/parameters/OscA/PitchColumn.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/parameters/OscB/PitchColumn.java

wip keytrck rework

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/parameters/LabelSmall.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/ParameterInfoDialog.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/html/presetSearch/PresetSearch.ui.xml
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/html/presetSearch/PresetSearchDialog.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/html/setup/SetupDialog.java
NonMaps/src/war/NonMaps.css
NonMaps/src/war/style.css

fixes #658

---

playground/src/presets/PresetManager.cpp
playground/src/presets/PresetManager.h
playground/src/proxies/hwui/panel-unit/boled/setup/ImportBackupEditor.cpp

fixes #606

---

playground/src/proxies/hwui/HWUI.cpp
playground/src/proxies/hwui/HardwareUserInterfaceUnit.cpp

fixes #667

---

playground/src/presets/BankActions.cpp

WebUI: Delete Presets -> prompt delete Bank, Fixed

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/PresetList.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/preset/Preset.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/undo/UndoTree.java
playground/src/libundo/undo/Transaction.cpp
playground/src/libundo/undo/Transaction.h

 Presetlist updates now on highlight in search dialog

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/preset/Preset.java

added initial impl of ticket 960

---

playground/src/parameters/Parameter.cpp

added more sophisticated isChanged algorithm to use an epsilon for comparing the 2 doubles
#709

BOLED: Parameter isChangedFromLoaded fix false positves

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/ServerProxy.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/dataModel/BooleanDataModelEntity.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/dataModel/editBuffer/BasicParameterModel.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/dataModel/editBuffer/EditBufferModel.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/dataModel/editBuffer/EditBufferUpdater.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/dataModel/editBuffer/ParameterUpdater.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/presenters/ParameterPresenter.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/presenters/ParameterPresenterProvider.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/useCases/PresetRecall.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/Name.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/RGB.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/parameters/Parameter.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/ParameterCompareButton.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/BeltParameterLayout.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/RecallArea.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BeltPresetLayout.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouter.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterL.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterM.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterS.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterXL.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterXS.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterXXL.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetBeltLayouterXXS.java
playground/src/libundo/undo/Transaction.cpp
playground/src/libundo/undo/Transaction.h
playground/src/parameters/Parameter.cpp
playground/src/parameters/Parameter.h
playground/src/presets/EditBufferActions.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp

WebUI: Changed + Recall

---

playground/src/presets/Preset.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/AppendOverwriteInsertButtonMenu.cpp

failing insert rename now works by selecting the stored preset

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/ServerProxy.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/CompareDialog.java
playground/src/device-settings/DebugLevel.h
playground/src/device-settings/WifiSetting.cpp
playground/src/http/ContentManager.cpp
playground/src/http/HTTPServer.cpp
playground/src/http/MCViewContentManager.h
playground/src/parameters/MacroControlParameter.cpp
playground/src/parameters/MacroControlParameter.h
playground/src/parameters/Parameter.cpp
playground/src/parameters/Parameter.h
playground/src/playground.h
playground/src/presets/BankActions.cpp
playground/src/presets/EditBuffer.cpp
playground/src/presets/EditBuffer.h
playground/src/presets/EditBufferActions.cpp
playground/src/presets/PresetManagerActions.cpp
playground/src/presets/PresetManagerActions.h
playground/src/proxies/hwui/FourStateLED.cpp
playground/src/proxies/hwui/base-unit/BaseUnit.h
playground/src/proxies/hwui/panel-unit/PanelUnitParameterEditMode.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MultiLineLabel.h
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterCarousel.cpp
playground/src/proxies/hwui/panel-unit/boled/setup/WiFiSettingView.cpp
playground/src/tools/SpawnCommandLine.cpp
playground/src/tools/SpawnCommandLine.h

fixed Preset - Edit-Buffer inconsistency in compare

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Tape.java

cleanup and change impl of getMostInterestingTape

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/PresetManager.java

fixed loadbutton state with init sound

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/PresetManager.java

added Init name in WebUI if no preset is loaded

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetManagerContextMenu.java

changed bug hack-around to be used on all platform

---

playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankEditButtonMenu.cpp

fixed missing focus and mode update after every bank deletion

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Bank.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Tape.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/menu/GlobalMenu.java

bank over insert tape now colors both tapes active

---

playground/src/device-settings/AccessPointRestarter.cpp
playground/src/device-settings/AccessPointRestarter.h

Change initialization of std::atomic bool

---

NonMaps/MCView/new.html
NonMaps/MCView/new.js
NonMaps/MCView/style.css

787 - 790 (MCView)

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/BeltParameterLayout.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/ModulationSourceButton.java

fixes #801

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/presenters/PresetManagerPresenter.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/presenters/PresetManagerProvider.java

#791 && #780 treten nicht mehr auf

renamed class called PresetManager to PresetManagerProvider because he is

---

audio-engine/CMakeLists.txt

cmake creates a copy of the built executable with name

---

audio-engine/src/synth/c15-audio-engine/dsp_host.cpp
audio-engine/src/synth/c15-audio-engine/dsp_host_examine.h
audio-engine/src/synth/c15-audio-engine/paramengine.cpp
audio-engine/src/synth/c15-audio-engine/paramengine.h

This adds an interface to the param_head and param_body arrays, so we are able to change memory layout behind the interface of 
paramengine::getHead, paramengine::getBody and paramengine::getSignal.

Add params iface

---

playground/src/presets/EditBuffer.cpp
playground/src/presets/RecallParameterGroups.cpp
playground/src/presets/RecallParameterGroups.h

fix onChange in RecallSet to be processed inside Transaction

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/dataModel/presetManager/PresetSearch.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/presenters/PresetSearch.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/presenters/PresetSearchProvider.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/useCases/PresetSearch.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/preset/Preset.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/html/presetSearch/PresetSearch.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/html/presetSearch/PresetSearch.ui.xml

add load current search highlight preset checkbox and usecases

---

playground/src/presets/Bank.cpp

add default for bank name: <Untitled Bank>

---

playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ModulateableParameterRecallControls/RecallMCAmountLabel.cpp

removed wrong mc-amount recall scaling for bipolar parameters

---

playground/src/http/UndoScope.cpp
playground/src/http/UndoScope.h
playground/src/parameters/ModulateableParameter.cpp
playground/src/parameters/ModulateableParameter.h
playground/src/presets/EditBuffer.cpp

move call to EditBufferSnapshotMaker::addSnapshotIfRequired to only EditBuffer::copyFrom

---

audio-engine/src/synth/c15-audio-engine/dsp_host.cpp
audio-engine/src/synth/c15-audio-engine/pe_defines_config.h

similar to [dsp_optimation] fix, got rid of glitchy pitch behavior for key events and hw note shift

[master] fixed glitchy pitch bevahior for key down and note shift

---

audio-engine/src/Options.cpp
playground/src/Options.cpp

corrects bbbb argument to match other calling conventions
remove unnecessary information from argument descriptions, rework

cleanup program arguments

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/ParameterInfoDialog.java
NonMaps/src/war/NonMaps.css

Macro control title can now be selected and copied -> special symbols A-D accessible

WebUI: Parameter Info: Macro control title selectable

---

NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/PresetManager.java
NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/Belt.java

fixed inplace store hotkey

---

audio-engine/systemd/audio-engine.service.in

See doc in https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=

Endlessly try to restart audio-engine

---

audio-engine/systemd/audio-engine.service.in

Is this also needed in the Master Branch?

Include Heartbeat MIDI-HDW per Default

---

NonMaps/MCView/new.js

#1126 
To implement: switch part (Voice Group Selection) for split and layer presets

updated mc view to support 6 mc's

---

playground/src/proxies/lpc/LPCProxy.cpp
playground/src/proxies/lpc/LPCProxy.h
playground/src/proxies/lpc/MessageParser.cpp
playground/src/proxies/lpc/MessageParser.h

Heartbeat was successfully tested in with LPC software version 103

Fix Heatbeat implementation 

---

playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/AppendOverwriteInsertButtonMenu.cpp

fix append overwrite insert bug

---

playground/resources/templates/sound/select/single/SingleSoundLayout_A.json

highlight convert to button

---

NonMaps/src/main/java/com/nonlinearlabs/client/dataModel/editBuffer/EditBufferModel.java
NonMaps/src/main/java/com/nonlinearlabs/client/dataModel/editBuffer/EditBufferModelUpdater.java
NonMaps/src/main/java/com/nonlinearlabs/client/presenters/EditBufferPresenter.java
NonMaps/src/main/java/com/nonlinearlabs/client/presenters/EditBufferPresenterProvider.java
NonMaps/src/main/java/com/nonlinearlabs/client/presenters/ParameterPresenterProvider.java
NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/LayerSoundLayout.java
NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SoundTypeMenu.java
NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SplitSoundLayout.java
NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/soundSettings/SoundSettings.ui.xml
NonMaps/src/main/webapp/NonMaps.js
playground/src/parameters/scale-converters/dimension/NoteWithOctaveDimension.cpp
playground/src/presets/EditBuffer.cpp

fixes #1062
- respect part names
- color voice group settings in belt
- fix sound type menu so it cannot convert from split to layer and vice versa anymore
- fix split point display value

WebUI polishing regarding dual mode

---

playground/src/parameters/scale-converters/ParabolicGainDbScaleConverter.cpp
playground/src/parameters/scale-converters/ParabolicGainDbScaleConverter.h
playground/src/presets/EditBuffer.cpp
playground/src/testing/unit-tests/EditBufferTests.cpp
playground/src/testing/unit-tests/ParabolicGainDbScaleConvertertests.cpp

add display values and convert back to control position
fixes #1196

fixed master volume conversion 

---

audio-engine/src/synth/C15Synth.cpp
bbbb/src/Application.cpp
bbbb/src/Options.cpp
bbbb/src/Options.h
bbbb/src/ui/Key.cpp
bbbb/src/ui/Key.h
bbbb/src/ui/Keyboard.cpp
bbbb/src/ui/Keyboard.h
bbbb/src/ui/Window.cpp
bbbb/src/ui/Window.h
nltools/include/nltools/messaging/Message.h
nltools/include/nltools/messaging/Messaging.h

Adding software MIDI-Keyboard to BBBB

---

playground/src/proxies/hwui/HWUI.cpp
playground/src/proxies/hwui/HWUI.h

remove edit mode on focus change

---

playground/src/presets/EditBuffer.cpp
playground/src/testing/unit-tests/EditBufferTests.cpp

changed init to set voice group labels to 'Init'

---

playground/src/parameters/RibbonParameter.cpp
playground/src/parameters/RibbonParameter.h
playground/src/testing/unit-tests/PedalModeReturnTests.cpp

fixed multiple bidirectional routing bug

---

playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ModulationRoutersCarousel.cpp

changed mc routing order in carousel

---

playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/DualSoundEditMenu.cpp

added init sound for dual sound

---

audio-engine/src/synth/c15-audio-engine/paramengine.cpp

fixed spreading table for unison phase according to LPV v7

fixed unison phase spread table (milestone 1.5)

---

audio-engine/src/synth/c15-audio-engine/unison_spread_table.h

fixed spreading table for unison phase according to LPV v7

fixed unison phase spread table (milestone 1.7)

---

playground/src/device-settings/AutoLoadSelectedPreset.cpp
playground/src/device-settings/AutoLoadSelectedPreset.h
playground/src/presets/BankActions.cpp
playground/src/presets/PresetManager.cpp
playground/src/presets/PresetManager.h
playground/src/presets/PresetManagerActions.cpp
playground/src/proxies/hwui/base-unit/BaseUnitPresetsAndBanksMode.cpp
playground/src/proxies/hwui/base-unit/BaseUnitPresetsAndBanksMode.h
playground/src/proxies/hwui/base-unit/BaseUnitPresetsMode.cpp
playground/src/proxies/hwui/base-unit/soled/BanksLayout.cpp
playground/src/proxies/hwui/base-unit/soled/DirectLoadIndicator.h
playground/src/proxies/hwui/base-unit/soled/PresetsLayout.cpp
playground/src/proxies/hwui/descriptive-layouts/events/GlobalEventSinkBroker.cpp
playground/src/proxies/hwui/descriptive-layouts/events/PresetManagerEvents.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp
playground/src/testing/unit-tests/settings/LoadPresetModeSetting.cpp

changed direct load setting to include new 'LoadPart' mode. DirectLoad On and Off are DirectLoad / SelectPreset respectively

WIP Direct Load Setting

---

playground/src/groups/UnisonGroup.cpp
playground/src/parameters/UnisonVoicesParameter.cpp
playground/src/parameters/UnisonVoicesParameter.h
playground/src/presets/EditBuffer.cpp
playground/src/presets/EditBuffer.h
playground/src/serialization/EditBufferSerializer.cpp
playground/src/serialization/EditBufferSerializer.h

added unison voices callback

---

playground/src/parameters/mono-mode-parameters/MonoGlideTimeParameter.cpp

fixed scaling

---

playground/src/parameters/mono-mode-parameters/MonoPriorityParameter.cpp

mono priority: set default to 0.5

---

playground/src/device-settings/LoadModeSetting.h
playground/src/device-settings/LoadPresetSetting.cpp
playground/src/groups/FBMixerGroup.cpp
playground/src/groups/OutputMixerGroup.cpp
playground/src/groups/VoiceGroupMasterGroup.cpp
playground/src/parameters/Parameter.cpp
playground/src/presets/EditBuffer.cpp
playground/src/presets/EditBuffer.h
playground/src/testing/unit-tests/EditBufferTests.cpp

changed fbmixer param defaults
moved toFX parameter into correct group
changed slider types for new FB src params
prevent auto load while toggling the load mode -> from button

fix parameters and direct load

---

audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
parameter-db/generated/c15_config.h
parameter-db/generated/parameter_declarations.h
parameter-db/generated/parameter_descriptor.h
parameter-db/generated/parameter_info.h
parameter-db/generated/parameter_list.h

- enabled rigorous midi logging
- fixed cabinet ctrl signals

Engine additions and fixes

---

nltools/include/nltools/messaging/Message.h
playground/src/proxies/audio-engine/AudioEngineProxy.cpp

extracted mono enable parameter in message

---

playground/src/parameters/UnisonVoicesParameter.cpp
playground/src/parameters/UnisonVoicesParameter.h

added send document details on scale update for unison voices parameter

---

playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.h
playground/src/proxies/hwui/panel-unit/boled/preset-screens/SelectVoiceGroupLayout.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/SelectVoiceGroupLayout.h
playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetListEntry.cpp

add loading animation to load to part load

---

playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableParameterLayouts.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.h

fixup parameter-carousel appearing of not suitable

---

playground/src/proxies/hwui/panel-unit/PanelUnitPresetMode.cpp

added connection to hwui part selection for active overview

---

NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/Name.java
NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/Preset.java
NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/TypeLabel.java
NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/BeltPreset.java
NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/TypeLabel.java

added type labels for webui

---

audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
nltools/include/nltools/messaging/Message.h
playground/src/presets/EditBuffer.cpp
playground/src/proxies/audio-engine/AudioEngineProxy.cpp
playground/src/proxies/audio-engine/AudioEngineProxy.h
playground/src/proxies/hwui/controls/SwitchVoiceGroupButton.cpp
playground/src/proxies/hwui/controls/SwitchVoiceGroupButton.h
playground/src/proxies/hwui/descriptive-layouts/events/GlobalEventSinkBroker.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableParameterLayouts.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MonoModeParameterLayout.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MonoModeParameterLayout.h
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/UnisonParameterLayouts.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/UnisonParameterLayouts.h
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MonoParameterCarousel.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MonoUnisonModuleCaption.cpp
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MonoUnisonModuleCaption.h
playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/UnisonParameterCarousel.cpp
playground/src/testing/unit-tests/PresetMessageTests.cpp
playground/src/testing/unit-tests/parameters/ParameterInvariantTests.cpp

@MatthiasSeeber bitte hier anmerken was in der Audio-Engine kaputt gegangen sein kann. 
TODO before merge:

Cleanup layer

---

bbbb/src/Options.cpp

@KlausStrohhaecker der fix für den auftretenden crash in der BBBB.

fixes crashing bbbb

---

NonMaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
NonMaps/src/main/java/com/nonlinearlabs/client/presenters/EditBufferPresenter.java
NonMaps/src/main/java/com/nonlinearlabs/client/presenters/EditBufferPresenterProvider.java
NonMaps/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
NonMaps/src/main/java/com/nonlinearlabs/client/world/RGB.java
NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/Preset.java
NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/Overlay.java
playground/src/presets/EditBuffer.cpp
playground/src/presets/EditBuffer.h
playground/src/presets/EditBufferActions.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.h
playground/src/proxies/hwui/panel-unit/boled/preset-screens/SelectVoiceGroupLayout.cpp
playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetListEntry.cpp

Webui add part indication

---

playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankAndPresetNumberLabel.cpp

added current voice group to preset and bank label

---

bbbb/systemd/bbbb.service.in
playground/systemd/playground.service.in

updated services

---

playground/src/proxies/hwui/controls/SwitchVoiceGroupButton.cpp
playground/src/proxies/hwui/controls/SwitchVoiceGroupButton.h
playground/src/proxies/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferUIEvents.h

fixes #1353 
fixes #1359 (Dublette)

fixes #1353

---

playground/src/parameters/ModulateableParameter.cpp
playground/src/parameters/ModulateableParameter.h
playground/src/parameters/SplitPointParameter.cpp
playground/src/parameters/SplitPointParameter.h

fixes #1363

---

NonMaps/MCView/new.js

Split ID like "Global-243" and use second half as numeric id

fixed MC Values Playground to MC View (fixes #1378)

---

playground/src/presets/EditBuffer.cpp
playground/src/testing/unit-tests/dual-mode-acceptance/LoadDualPartIntoDualPart.cpp

fixup load to part -> master conversion

---

NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/PlayControls/MacroControls/MacroControlParameter.java
playground/src/device-settings/PresetGlitchSuppression.cpp

fixes #1411
+ small hotfix: change preset-glitch-suppression to default on

WebUI: fixed macro control given names

---

playground/src/groups/ParameterGroup.cpp

1417 fixup

---

projects/audio-engine/src/Options.cpp
projects/bbbb/src/Options.cpp
projects/playground/src/Options.cpp

added graceful option error handling
currently any parsing error is fine
TODO:
set sensible defaults for all parameters
Crash/Exit on missing values (if any)

WIP: Option Parsing

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/Preset.java

fixes 1520

---

projects/nltools/include/nltools/messaging/Messaging.h
projects/nltools/include/nltools/threading/ContextBoundMessageQueue.h
projects/nltools/src/nltools/messaging/Messaging.cpp
projects/nltools/src/nltools/messaging/OutChannel.h
projects/nltools/src/nltools/messaging/websocket/WebSocketOutChannel.cpp
projects/nltools/src/nltools/messaging/websocket/WebSocketOutChannel.h
projects/nltools/src/nltools/threading/ContextBoundMessageQueue.cpp
projects/playground/src/Application.cpp
projects/playground/src/proxies/hwui/FourStateLED.cpp
projects/playground/src/proxies/hwui/FourStateLED.h
projects/playground/src/proxies/hwui/TwoStateLED.cpp
projects/playground/src/proxies/hwui/base-unit/LowerRibbon.cpp
projects/playground/src/proxies/hwui/base-unit/Ribbon.cpp
projects/playground/src/proxies/hwui/base-unit/Ribbon.h
projects/playground/src/testing/unit-tests/HWUI/RibbonTests.cpp

#1510 (switch on the LEDs, clear the OLED)

flush messages to hwui on playground shut down

---

projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/presets/EditBuffer.h
projects/playground/src/testing/unit-tests/dual-mode-acceptance/ConvertSingleToDualSounds.cpp
projects/playground/src/testing/unit-tests/parameters/VoiceGroupMasterInvariantTests.cpp

set fade from explicitly on conversion to lay…er sound

fixed conversion bug 

---

projects/playground/src/proxies/hwui/descriptive-layouts/events/GlobalEventSinkBroker.cpp

invert inc / dec layer mute

---

projects/playground/src/proxies/hwui/descriptive-layouts/ConditionRegistry.cpp
projects/playground/src/proxies/hwui/descriptive-layouts/GenericLayout.cpp
projects/playground/src/proxies/hwui/descriptive-layouts/GenericLayout.h

by brute forcing the layouts -> triggered by an differed send so that all conditions are updated
closes #1519

fixes #1519 

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/dataModel/editBuffer/EditBufferModel.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/dataModel/editBuffer/EditBufferModelUpdater.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/Preset.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/PresetName.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/LayerSoundLayout.java
projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/presets/EditBuffer.h
projects/playground/src/presets/Preset.cpp
projects/playground/src/presets/Preset.h
projects/playground/src/proxies/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferEvents.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetListEntry.cpp

implemented #1545

---

projects/CMakeLists.txt

changed git date format to software version to be human readable

---

projects/acceptance-tests/src/Performance.cpp
projects/audio-engine/src/synth/C15Synth.cpp
projects/audio-engine/src/synth/C15Synth.h
projects/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
projects/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h

- LPC MIDI Key Messages are now simulated
- AudioEngine now counts samples (as a debug measure)

acceptance-tests : proposals

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/CustomPresetSelector.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/LoadToPartMode.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/StoreSelectMode.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/WebSocketConnection.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/MonoAndUnison/UnisonAndMonoControls.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/Bank.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/Header.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/Preset.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/GWTDialog.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/BankControl.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/BeltPreset.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/PresetList.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/StorePreset.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SplitSoundLayout.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/pointer/RightDrag.java

@schlenkibus I did not test it at all. The PR is more like an idea - if you like it you can merge it and then finalize.

add interface in order to avoid code duplications

---

projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankButton.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetTypeLabel.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetTypeLabel.h

closes #1626

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/SVFilter/LittleKnobSlider.java

closes #1631

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/Rect.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/ValueEdit.java

closes #1628

---

projects/playground/src/proxies/hwui/HWUI.cpp
projects/playground/src/proxies/hwui/HWUI.h
projects/playground/src/proxies/hwui/UsageMode.cpp
projects/playground/src/proxies/hwui/UsageMode.h
projects/playground/src/proxies/hwui/panel-unit/PanelUnit.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp

closes #1633

---

projects/playground/src/proxies/hwui/controls/BarSlider.cpp

closes #1652

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.h

closes #1653

---

projects/playground/resources/templates/sound/voices/VoicesLayout.json
projects/playground/resources/templates/sound/voices/VoicesLayoutLayer.json

closes #1655

---

projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/proxies/hwui/controls/SwitchVoiceGroupButton.cpp

fixes #1655

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/dataModel/ValueUpdater.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/ParameterValueSlider.java
projects/playground/src/parameters/Parameter.cpp

fixes hw amount boolean slider

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/MonoAndUnison/MonoControls.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/MonoAndUnison/UnisonAndMonoModuleHeader.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/MonoAndUnison/UnisonControls.java

fixes #1654

---

projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/testing/unit-tests/dual-mode-acceptance/LoadSingleIntoDualPart.cpp
projects/playground/src/testing/unit-tests/dual-mode-acceptance/MasterVolumeTuneModulationAspectConversionLoading.cpp

fixup #1585

---

projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/testing/unit-tests/dual-mode-acceptance/LoadSingleIntoDualPart.cpp
projects/playground/src/testing/unit-tests/dual-mode-acceptance/MasterVolumeTuneModulationAspectConversionLoading.cpp

Reverts nonlinear-labs-dev/C15#1665
Sorry @MatthiasSeeber - didn't see your comment (still have to learn reviewing on mobile phone)

Revert "fixup #1585"

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/LoadToPartMode.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/Overlay.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SoundTypeMenu.java

closes #1663

---

projects/playground/src/proxies/hwui/base-unit/BaseUnitPresetsMode.cpp

closes #1438

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp

fixes #1632

---

projects/playground/src/presets/Preset.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp

fixes #1646

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/Overlay.java

fixup #1682

---

projects/playground/src/proxies/hwui/HWUI.cpp
projects/playground/src/proxies/hwui/descriptive-layouts/GenericLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/PanelUnitPresetMode.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MuteIndicator.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MuteIndicator.h

closes #1689 & #1685

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ScaleParameterLayout.cpp

closes #1691

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/Overlay.java

move Part indication border one pixel up if belt is hidden 

---

projects/audio-engine/src/synth/c15-audio-engine/ae_poly_section.cpp
projects/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
projects/audio-engine/src/synth/c15-audio-engine/key_event.h
projects/audio-engine/src/synth/c15-audio-engine/voice_allocation.h

AudioEngine (Single) Glide Fix

---

projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/testing/unit-tests/dual-mode-acceptance/PartLabelSurviveConvert.cpp

closes #1718

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/settings/DeveloperSettings.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/settings/TestHWUIDisplay.java
projects/playground/src/device-settings/SettingsActions.cpp
projects/playground/src/proxies/hwui/FrameBuffer.cpp
projects/playground/src/proxies/hwui/TestLayout.cpp
projects/playground/src/proxies/hwui/TestLayout.h

added draw rects to developer options 

---

projects/playground/src/presets/EditBuffer.cpp

... also try to avoid exceptions when 'error' case is actually expected

try to improve readability

---

projects/playground/src/groups/MacroControlsGroup.cpp
projects/playground/src/groups/MacroControlsGroup.h
projects/playground/src/parameters/MacroControlParameter.cpp
projects/playground/src/parameters/MacroControlParameter.h
projects/playground/src/parameters/MacroControlSmoothingParameter.cpp
projects/playground/src/parameters/MacroControlSmoothingParameter.h
projects/playground/src/proxies/hwui/controls/ControlOwner.cpp
projects/playground/src/proxies/hwui/controls/ControlOwner.h
projects/playground/src/proxies/hwui/panel-unit/PanelUnitParameterEditMode.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlSmoothingParameterLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlSmoothingParameterLayout.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MacroControlEditButtonMenu.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MacroControlEditButtonMenu.h

closes #1593, rework mc smoothing layout

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.h

fixup 1593

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.h
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetTypeLabel.cpp

Issue 1745

---

projects/bbbb/CMakeLists.txt
projects/bbbb/systemd/gettimefromepc.service.in
projects/scripts/bbb/gettimefromepc.sh

BBB should be getting the time from ePC, helps looking through the journal.
I am really uncertain about the CMake logic ... so please take a  closer look at the new lines.

BBB time from the ePC

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/PlayControlParameterLayouts.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/PlayControlParameterLayouts.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/PhysicalControlBehaviorLabel.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/PhysicalControlBehaviorLabel.h

issue #1594

---

projects/playground/src/groups/MacroControlsGroup.cpp
projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/presets/EditBuffer.h
projects/playground/src/proxies/hwui/controls/BarSlider.h
projects/playground/src/proxies/hwui/controls/SelectedParameterValue.cpp
projects/playground/src/proxies/hwui/controls/SelectedParameterValue.h
projects/playground/src/proxies/hwui/controls/Slider.cpp
projects/playground/src/proxies/hwui/controls/Slider.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/Carousel.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/Carousel.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ModulationModeButton.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ModulationModeButton.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterNotAvailableInSoundInfo.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SelectedParameterBarSlider.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SelectedParameterBarSlider.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SelectedParameterDotSlider.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SelectedParameterDotSlider.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SelectedParameterKnubbelSlider.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SelectedParameterKnubbelSlider.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.h

fixes #1751

---

projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/testing/unit-tests/EditBufferTests.cpp
projects/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadSingleToLayerSoundTests.cpp
projects/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadSingleToSplitSoundTests.cpp

fixes #1762

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableParameterLayouts.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/PlayControlParameterLayouts.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/UnmodulatebaleParameterLayouts.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MacroControlEditButtonMenu.cpp

closes #1768
closes #1769
closes #1767

fixes tickets #1768, #1769, #1767

---

projects/playground/src/proxies/hwui/descriptive-layouts/primitives/Text.cpp
projects/playground/src/proxies/hwui/descriptive-layouts/primitives/Text.h

fixes #1775

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp

fixes #1780

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp

fixes #1781

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/dataModel/editBuffer/EditBufferModelUpdater.java
projects/playground/src/libundo/undo/Transaction.cpp
projects/playground/src/libundo/undo/Transaction.h
projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/presets/EditBuffer.h
projects/playground/src/presets/EditBufferActions.cpp
projects/playground/src/presets/SendEditBufferScopeGuard.cpp
projects/playground/src/presets/SendEditBufferScopeGuard.h

cleanup slected voicegroup for UI on sound type convert / change of soundtype detected, closes #1774

issue 1774

---

projects/playground/resources/templates/sound/select/single/SingleSoundLayout.json
projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/presets/EditBuffer.h
projects/playground/src/proxies/hwui/descriptive-layouts/TemplateEnums.h
projects/playground/src/proxies/hwui/descriptive-layouts/events/GlobalEventSourceBroker.cpp
projects/playground/src/proxies/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferEvents.cpp
projects/playground/src/proxies/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferEvents.h

fixup #1779

---

projects/playground/src/presets/EditBuffer.cpp

fixes #1798

---

projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/presets/EditBuffer.h
projects/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadDualPresetPartIntoLayerSoundTests.cpp

Issue 1796

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/OscA/FluctColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/OscB/FluctColumn.java

fixes #1809

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/Overlay.java
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetListHeader.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetTypeLabel.cpp

fixes #1812 and align mute symbol webui aswell

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/ChoosePresetPartDialog.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/Preset.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/LayerSoundLayout.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SplitSoundLayout.java

added preset drag'n'drop to soundbelt & layer belt graphics

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/presenters/EditBufferPresenterProvider.java
projects/playground/src/presets/EditBuffer.cpp

closes #1815

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/FBMixer/FBMixerColumn4.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulateableSliderHorizontal.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/SliderHorizontal.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/MCSourceDisplay.java

fixes #1810

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/ValueEdit.java

closes #1799

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/LoadModeMenu.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/LoadModeMenu.h

fixes #1831

---

projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetInfoContent.cpp

fixes preset info crash of old presets, closes #1832

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/Scale/ScaleParameter.java
projects/NonMaps/src/main/webapp/NonMaps.js
projects/playground/src/parameters/scale-converters/BaseKeyScaleConverter.cpp
projects/playground/src/parameters/scale-converters/dimension/NoteDimensionIgnoreOctave.cpp
projects/playground/src/parameters/scale-converters/dimension/NoteDimensionIgnoreOctave.h

closes #1839

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/LayerSoundLayout.java
projects/playground/src/presets/EditBufferActions.cpp
projects/playground/src/proxies/hwui/descriptive-layouts/events/GlobalEventSinkBroker.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetTypeLabel.cpp

Issue 1838

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulationSourceSwitch.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/MonoAndUnison/MonoColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/Parameter.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/Scale/ScaleParameter.java

fixes #1856, fixes #1854

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/PlayControlParameterLayouts.cpp

fixed highlight of parameter label in hw source layout
closes #1857

fixes #1857

---

projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/LoadModeMenu.cpp

closes #1858

---

projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetTypeLabel.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetTypeLabel.h

updated load to part color

---

projects/bbbb/src/io/WiFiManager.cpp
projects/bbbb/src/io/WiFiManager.h
projects/nltools/include/nltools/messaging/Message.h
projects/playground/src/device-settings/Passphrase.cpp
projects/playground/src/device-settings/Passphrase.h
projects/playground/src/device-settings/SSID.cpp

removed unnecessarily complex ssid and password logic 

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/settings/DeveloperSettings.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/settings/ExportBoled.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/settings/ExportSoled.java
projects/playground/CMakeLists.txt
projects/playground/src/http/HTTPServer.cpp
projects/playground/src/http/ServedFile.cpp
projects/playground/src/presets/EditBufferActions.cpp
projects/playground/src/proxies/hwui/FrameBuffer.cpp
projects/playground/src/proxies/hwui/FrameBuffer.h
projects/playground/src/proxies/hwui/HWUI.cpp
projects/playground/src/proxies/hwui/HWUI.h

closes #1875 
TODO: change bbbb and exported color pallete to match real colors on HW displays (white instead of yellow)

added boled and soled download via webui

---

projects/playground/src/presets/PresetManager.cpp
projects/playground/src/presets/PresetManager.h
projects/playground/src/proxies/hwui/HWUI.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.h
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.h
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankButton.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/LoadToPartPresetList.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetTypeLabel.cpp

Issue 1874

---

build-tools/create-c15-update/update_scripts/bbb_update.sh
projects/scripts/bbb/install-update.sh

Prevents the update from clearing journal on the BBB

Protect journal

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/LayoutResizingVertical.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/CombFilter/CombFilterCol3.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/LabelModulationSource.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulatableHorizontalSlider.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulatableParameter.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulatableParameterWithoutName.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulateableKnobWithoutHeader.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulateableSmallKnobParameter.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulationSourceLabel.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/OscA/OscAControls.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/OscA/PhaseColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/OscB/FluctColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/OscB/OscBControls.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/OscB/PhaseColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeA/AsymColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeA/DriveExtColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeA/FBMixAndRingModColumns.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeA/FBMixColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeA/FoldAsymMixColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeA/RingModColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeA/ShapeAControls.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeB/AsymColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeB/DriveExtColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeB/FBMixAndRingModColumns.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeB/FBMixColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeB/FoldAsymMixColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeB/RingModColumn.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ShapeB/ShapeBControls.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/TripleParameterColumn.java

Issue 1884

---

projects/playground/src/parameters/Parameter.cpp
projects/playground/src/parameters/Parameter.h
projects/playground/src/parameters/SplitPointParameter.cpp
projects/playground/src/parameters/SplitPointParameter.h
projects/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/items/controls/SplitPointLabel.cpp
projects/playground/src/proxies/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferUIEvents.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
projects/playground/src/testing/unit-tests/parameters/SplitPointTests.cpp

fixes #1900

---

projects/playground/src/proxies/hwui/controls/SwitchVoiceGroupButton.cpp

fixes #1898

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.h
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp

fixes #1896

---

projects/playground/src/parameters/MacroControlParameter.cpp

closes #1897
@hhoegelo kannst du diesen fix lokal bei dir verifizieren? (die messages sehen gut aus)

closes #1897

---

projects/playground/src/parameters/ModulationRoutingParameter.cpp
projects/playground/src/parameters/RibbonParameter.cpp

Fix send ribbon pos to audio enigne on exclusive routing lost

---

projects/playground/resources/templates/sound/voices/VoicesLayout.json
projects/playground/resources/templates/sound/voices/controls/SplitVoiceGroupIndication.json

updated split voice group indication to be same size and position as preset and parameter indication
closes #1919

fixes #1919

---

projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetListEntry.cpp

fixes #1925

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/presenters/EditBufferPresenterProvider.java

fixes #1963

---

build-tools/create-c15-update/update_scripts/run.sh
projects/bbbb/systemd/install-update-from-usb.service.in

Informs the User, that the Update will start (a bit friendlier) and stops the services without a BBB_Update dependency.

Update message and stop service

---

build-tools/create-c15-update/create-c15-update.sh

Remove stale folders which may contain zombies from previous builds
- top level update folder, typically "nonlinear-c15-update"
- BBB rootfs "build-tools/bbb/rootfs"

create-c15-update.sh : remove potential zombies

---

projects/lpc-tools/src/lpc.c
projects/lpc-tools/src/process-read-msgs.c
projects/realtime-system/src/co-proc/src/drv/nl_kbs.c
projects/realtime-system/src/main/src/drv/nl_dbg.c
projects/realtime-system/src/main/src/spibb/nl_bb_msg.c
projects/realtime-system/src/main/src/sys/nl_status.c
projects/realtime-system/src/main/src/sys/nl_status.h
projects/realtime-system/src/main/src/tcd/nl_tcd_adc_work.c
projects/realtime-system/src/main/src/tcd/nl_tcd_msg.c
projects/realtime-system/src/main/src/tcd/nl_tcd_msg.h
projects/realtime-system/src/main/src/tcd/nl_tcd_poly.c
projects/realtime-system/src/shared/drv/nl_cgu.h
projects/realtime-system/src/shared/ipc/emphase_ipc.h
projects/realtime-system/src/shared/sys/nl_version.h
projects/scripts/bbb/keybursts.sh
projects/shared/globals.h
projects/shared/version.h

2020.06 LPC fix midi buffer overflow ("Beta 20-25 RC03")

---

projects/realtime-system/src/main/src/spibb/nl_spi_bb.c
projects/realtime-system/src/main/src/tcd/nl_tcd_poly.c

closes #2018 
Workaround only, pending root cause fix

2020.06 empty dma packet workaround

---

projects/playground/src/parameters/Parameter.cpp

fixes #2024 by storing quantized value instead of raw random CP

---

projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/LoadToPartPresetList.cpp

Issue 2030

---

projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableParameterLayouts.cpp

fixes #2026

---

projects/NonMaps/MCView/new.js

fixes #2044

---

projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp

fixes #2045

---

projects/playground/src/proxies/hwui/controls/Control.h
projects/playground/src/proxies/hwui/controls/ControlWithChildren.cpp
projects/playground/src/proxies/hwui/controls/ControlWithChildren.h
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterCarousel.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterNotAvailableInSoundInfo.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterNotAvailableInSoundInfo.h

Issue 2040

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/presenters/ParameterPresenterProvider.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/useCases/PresetRecall.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/recall/MCAmountRecallArea.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/recall/MCPositionRecallArea.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/recall/ParameterRecallArea.java
projects/playground/src/presets/EditBuffer.cpp
projects/playground/src/presets/EditBuffer.h
projects/playground/src/presets/EditBufferActions.cpp

and same bugs in category: setting values for supposedly selected parameter, this lead to bugs concerning one Part in BOLED selected and other in WebUI selected, now passing an ID is always needed

fixes #2056

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/LayerDisplay.java

fixes #2060

---

build-tools/create-c15-update/update_scripts/bbb_update.sh
build-tools/create-c15-update/update_scripts/epc_fix.sh
build-tools/create-c15-update/update_scripts/epc_pull_update.sh
build-tools/create-c15-update/update_scripts/epc_push_update.sh
build-tools/create-c15-update/update_scripts/lpc_update.sh
build-tools/create-c15-update/update_scripts/run.sh
projects/scripts/bbb/install-update.sh

Sorry for the late PR.
This one includes minimal changes, which improve the update behavior!   
Chose the wrong branch for the PR first ...

Update cosmetic repairs

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java
projects/shared/version.h

fixes #2075 
@schlenkibus please double check, if which of the online-help addresses is the correct one!

changed online help address for the ctrl+h key shortcut

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java

fixes #2078

---

projects/NonMaps/MCView/index.html
projects/NonMaps/MCView/new.js
projects/NonMaps/MCView/style.css

added MCView not connected indication

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ParameterEditor.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java

closes #2077

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/NonLinearWorld.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java
projects/playground/src/presets/UndoableVector.cpp
projects/playground/src/presets/UndoableVector.h

Issue 2077

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/presenters/DeviceSettings.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/presenters/DeviceSettingsProvider.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/useCases/SystemSettings.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml
projects/acceptance-tests/src/VoiceAllocation.cpp
projects/playground/src/device-settings/PresetGlitchSuppression.cpp

fixes #2091

---

build-tools/create-c15-update/update_scripts/epc_fix.sh
build-tools/create-c15-update/update_scripts/lpc_check.sh
build-tools/create-c15-update/update_scripts/lpc_update.sh
projects/playground/src/proxies/hwui/panel-unit/boled/setup/ExportBackupEditor.cpp
projects/shared/version.h

Issue 2094

---

projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/LoadToPartPresetList.cpp

closes #2103

---

projects/playground/src/presets/BankActions.cpp

fixes #2113

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/Preset.java

fixed unchecked cast in preset select, closes #2123

issue 2123

---

projects/playground/src/device-info/RTSoftwareVersion.cpp
projects/playground/src/proxies/lpc/LPCProxy.cpp
projects/playground/src/proxies/lpc/LPCProxy.h

added not received placeholder for RTVersion

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/CompareDialog.java

added compare dialog refresh on preset load

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/BeltParameterLayout.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/menu/GlobalMenu.java

add MCView shortcut: ctrl+m

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/Mouseing.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/NonLinearWorld.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/ShiftMultiplePresetSelection.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/Preset.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/BeltPreset.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/presetSearch/PresetSearch.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/presetSearch/PresetSearchDialog.java

TODO investigate shift differences across browsers / OS's
fixes #2138 
fixes #2131

Issue 2138

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/NonLinearWorld.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java

added double click zoom and restore zoom again, closes #2145

---

projects/NonMaps/src/main/webapp/NonMaps.html
projects/NonMaps/src/main/webapp/index_noscript.html

todo: create design and manual reference for javascript settings (about:config / chrome:settings / addons?)

added noscript webpage -> if javascript is disabled

---

projects/bbbb/src/io/FromLPCBridge.cpp
projects/playground/src/proxies/hwui/base-unit/soled/PlayOrEditModeLayout.cpp
projects/playground/src/proxies/hwui/base-unit/soled/PlayOrEditModeLayout.h

@Matthias does that behavior work as you intended it to be?
+ fix for BBBB emulation ribbons, they did not work since the HW Source -> EHC umbau

fixes #2112

---

projects/playground/src/presets/Preset.cpp
projects/playground/src/presets/Preset.h
projects/playground/src/presets/PresetParameter.cpp
projects/playground/src/presets/PresetParameter.h

fix unison and mono compare of layer sounds

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/Mouseing.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/NonLinearWorld.java

added more general shift and ctrl handling, on every event the state is captured now

Prevent stuck Shift modifier if shift is released without NonMaps Focus

---

projects/playground/src/parameters/PedalParameter.cpp
projects/playground/src/parameters/RibbonParameter.cpp
projects/playground/src/parameters/value/RawValue.cpp
projects/playground/src/parameters/value/RawValue.h

fixes #2027

---

projects/playground/src/presets/PresetManager.cpp

changed will not be true if no banks were present, now the manager itself will also play an role in that attribute

hotfix for deleting the last bank

---

projects/NonMaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/NonMaps/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
projects/playground/src/presets/EditBufferActions.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/LowerModulationBoundControl.cpp
projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/UpperModulationBoundControl.cpp

move limit change into mod-parameter, webui and hwui upper/lower limit changes are now more similar -> number of transactions / undo"

cleanup upper/lower-mod-limit undo transactions

---

projects/epc/playground/src/parameters/ModulateableParameter.cpp
projects/epc/playground/src/parameters/Parameter.cpp
projects/epc/playground/src/parameters/Parameter.h
projects/epc/playground/src/parameters/value/RawValue.cpp
projects/epc/playground/src/parameters/value/RawValue.h
projects/epc/playground/src/presets/EditBuffer.cpp
projects/epc/playground/src/presets/EditBufferActions.cpp
projects/epc/playground/src/presets/recall/RecallParameterGroups.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnitParameterEditMode.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableParameterLayouts.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/parameters/Parameter.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/BeltParameterLayout.java

setDefault now takes argument whether it was called from recall or default, and if default it will allow toggling
closes #1823

closes #1823

---

projects/epc/playground/src/testing/TestHelper.h
projects/epc/playground/src/testing/unit-tests/async/SpawnAsyncCommandLineTests.cpp
projects/epc/playground/src/testing/unit-tests/messaging/MessagingTests.cpp
projects/shared/nltools/include/nltools/system/AsyncCommandLine.h
projects/shared/nltools/include/nltools/system/SpawnAsyncCommandLine.h
projects/shared/nltools/src/nltools/system/AsyncCommandLine.cpp
projects/shared/nltools/src/nltools/system/SpawnAsyncCommandLine.cpp

moved doMainLoop into TestHelper
added SpawnAsyncCommandLine and AsyncCommandLine tests
exposed SpawnAsyncCommandLine::removeDone for housekeeping

add SpawnAsyncCommandLine and AsyncCommandLine Tests

---

build-tools/epc/createUpdate.sh

added webui to build update epc call

Fix WebUI build in create-c15-update

---

projects/epc/playground/src/presets/recall/RecallParameterGroups.cpp

closes #2186

---

.gitignore
projects/epc/playground/src/presets/recall/RecallParameterGroups.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterNotAvailableInSoundInfo.cpp

fixed parameter not available showing on edit screens and after exiting edit screens

Boled: Fix Broken Parameter Screens 

---

build-tools/epc/createUpdate.sh

fixed install of packages -> fuse was missing and lead to broken sshfs

---

.gitignore
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/parameters/PhysicalControlParameter.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/parameters/PlayControls/MacroControls/MacroControlParameter.java

closes #2181

---

projects/epc/playground/src/device-settings/ScreenSaverTimeoutSetting.cpp
projects/epc/playground/src/device-settings/ScreenSaverTimeoutSetting.h
projects/epc/playground/src/device-settings/Settings.cpp
projects/epc/playground/src/presets/EditBuffer.cpp
projects/epc/playground/src/presets/EditBuffer.h
projects/epc/playground/src/proxies/hwui/HWUI.cpp
projects/epc/playground/src/proxies/hwui/HWUI.h
projects/epc/playground/src/proxies/hwui/OLEDProxy.cpp
projects/epc/playground/src/proxies/hwui/OLEDProxy.h
projects/epc/playground/src/proxies/hwui/base-unit/soled/SOLED.cpp
projects/epc/playground/src/proxies/hwui/base-unit/soled/SOLED.h
projects/epc/playground/src/proxies/hwui/base-unit/soled/SOLEDScreenSaver.cpp
projects/epc/playground/src/proxies/hwui/base-unit/soled/SOLEDScreenSaver.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/BOLED.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/BOLED.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/BOLEDScreenSaver.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/BOLEDScreenSaver.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/ScreenSaverTimeControls.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/ScreenSaverTimeControls.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp

Issue 2031

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/BankContextMenu.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/PresetManagerContextMenu.java
projects/epc/web-ui/src/main/webapp/style.css

various WebUI fixes

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/useCases/IncrementalChanger.java

closes #2008

---

projects/epc/playground/src/groups/ParameterGroup.cpp
projects/epc/playground/src/parameters/Parameter.cpp
projects/epc/playground/src/parameters/Parameter.h
projects/epc/playground/src/proxies/hwui/controls/SelectedParameterValue.cpp
projects/epc/playground/src/proxies/hwui/controls/Slider.cpp
projects/epc/playground/src/proxies/hwui/controls/SwitchVoiceGroupButton.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableParameterLayouts.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MCSelectButton.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterCarousel.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterNotAvailableInSoundInfo.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SelectedParameterModAmount.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SelectedParamsMacroControlSlider.cpp

cleanup moved isDisabled into parameter
closes #2189

closes #2189

---

projects/epc/playground/src/presets/EditBufferActions.cpp

remove open sound layout on type conversion, closes #1753

issue 1753

---

projects/bbb/bridge/src/ui/Boled.cpp
projects/epc/playground/src/proxies/hwui/HWUI.cpp

now white / gray instead of yellow
export via bbbb and webui also now white

changed OLED emulation colors

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/parameters/Parameter.java

by not using global voice group focus but parameter voice-group

fixes #2229

---

build-tools/create-c15-update/update_scripts/bbb_update.sh
build-tools/create-c15-update/update_scripts/run.sh

Issue 2224

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/BeltSoundLayout.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/LayerSoundLayout.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SplitSoundLayout.java

rename part via double click on part label in sound belt
@hhoegelo 
it seems like i put the doubleClick handler into the wrong control at first

Issue 2223

---

projects/epc/playground/src/presets/Preset.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnit.cpp
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/CompareDialog.java

added part name to preset compare

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/ParameterInfoDialog.java

fixes #2233

---

projects/epc/audio-engine/src/synth/c15-audio-engine/ae_envelopes.h
projects/epc/audio-engine/src/synth/c15-audio-engine/ae_poly_fb_mix.cpp
projects/epc/audio-engine/src/synth/c15-audio-engine/ae_poly_section.cpp
projects/epc/audio-engine/src/synth/c15-audio-engine/ae_potential_improvements.h
projects/epc/audio-engine/src/synth/c15-audio-engine/signal_storage_dual.h

AudioEngine - improvements: first cleanup

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SplitSoundLayout.java

fixes #2271

---

projects/epc/audio-engine/src/synth/c15-audio-engine/ae_poly_section.cpp
projects/epc/audio-engine/src/synth/c15-audio-engine/ae_potential_improvements.h

AudioEngine - Part Muting only on Part Volume

---

projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
projects/epc/audio-engine/src/synth/c15-audio-engine/midi_handle.cpp
projects/epc/audio-engine/src/synth/c15-audio-engine/midi_handle.h

- migrated MIDI handling to separate file
- refactored Encoding and Decoding of 7-Bit (Aftertouch), true 14-Bit (Bender) and clipped 14-bit (remaining Sources)
- no cleanup yet
- first soundcheck worked as expected, further tests are needed

AudioEngine - MIDI CC Ammendments

---

projects/epc/audio-engine/src/synth/C15Synth.cpp
projects/epc/audio-engine/src/synth/C15Synth.h
projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
projects/epc/audio-engine/src/synth/c15-audio-engine/midi_handle.h
projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp

Feature midi cc

---

projects/epc/playground/resources/templates/sound/select/layer/LayerSoundLayout.json
projects/epc/playground/src/proxies/hwui/controls/FadeIndicator.cpp
projects/epc/playground/src/proxies/hwui/controls/FadeIndicator.h
projects/epc/playground/src/proxies/hwui/controls/PNGControl.cpp
projects/epc/playground/src/proxies/hwui/descriptive-layouts/ControlInstance.cpp
projects/epc/playground/src/proxies/hwui/descriptive-layouts/ControlRegistry.cpp
projects/epc/playground/src/proxies/hwui/descriptive-layouts/TemplateEnums.h
projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/GlobalEventSourceBroker.cpp
projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferEvents.cpp
projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferEvents.h

Issue 2287

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MacroControlEditButtonMenu.cpp

fixed selected mc edit button action

---

projects/epc/playground/src/parameters/SplitPointParameter.cpp
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/SplitValueDisplay.java

fixes #2317 and current part highlight of split value if cpI == cpII

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/fadeeditor/KeyBed.java

removed voice group interference when using fade editor

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableDualVoiceGroupMasterAndSplitPointLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableDualVoiceGroupMasterAndSplitPointLayout.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableParameterLayouts.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MCAssignedIndicator.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MCAssignedIndicator.h

changed mc assignment indicator 2308

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/PresetManagerPresenter.java

WebUI: added "converted" text to loaded preset label in preset-belt 

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SoundTypeMenu.java

WebUI: Change Sound Convert Item names

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java

WebUI: added shortcut for selecting VG I and II

---

projects/epc/playground/src/proxies/hwui/controls/FadeIndicator.cpp
projects/epc/playground/src/proxies/hwui/controls/FadeIndicator.h

changed fade indicator draw for VG II

---

projects/epc/playground/src/device-settings/SettingsActions.cpp
projects/epc/playground/src/device-settings/SyncSplitSettingUseCases.cpp
projects/epc/playground/src/device-settings/SyncSplitSettingUseCases.h
projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/menu/menu-items/SplitSyncItem.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SplitPointEditMenu.cpp
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/DeviceSettings.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/DeviceSettingsProvider.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/EditBufferPresenterProvider.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/Belt.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/BeltFadeEditorLayout.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/SoundBeltButton.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/BeltParameterLayout.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/ParameterContextMenu.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/SyncParameterButton.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SoundSettingsButton.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SplitSoundLayout.java

closes #2324 
closes #2313 
closes #2312
closes #2316

Fix fade bugs

---

projects/epc/playground/src/proxies/hwui/HWUI.cpp
projects/epc/playground/src/proxies/hwui/HWUI.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp

fixes #2318

---

projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferEvents.cpp
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/EditBufferPresenterProvider.java

closes #2338 -> stricter rules for ui indicator

closes #2338

---

projects/shared/nltools/src/nltools/messaging/websocket/WebSocketOutChannel.cpp

fixes context bound message queue ping bug that was dispatched from other thread than main.

fix threading issue

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SplitParameterValue.cpp
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/SplitValueDisplay.java

closes #2342

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/FadeEditorPresenter.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/FadeEditorPresenterProvider.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/fadeeditor/KeyBed.java

made fade editor react to last changed parameters: color gets put in front. Removed Selected Anfasser drawing (outline). closes #2328

WebUI: 2328

---

projects/epc/playground/src/proxies/hwui/controls/ControlOwner.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.h

removes mc - assignment indicator from mc-edit layout

closes #2358

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/Rect.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/ValueEdit.java

Issue 2361

---

projects/epc/playground/src/proxies/hwui/base-unit/soled/SOLEDScreenSaver.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/BOLEDScreenSaver.cpp

soled screensaver slower movement, and both screensaver-strings are now 'C15'

closes #2367

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/PresetContextMenu.java

Fixed bug that multiselection was active after deleting multiple-presets with DELETE-Key (context menu actions were fine)

fixes #2267

---

projects/epc/playground/src/presets/PresetManager.cpp
projects/epc/playground/src/presets/PresetManager.h
projects/epc/playground/src/presets/PresetManagerActions.cpp
projects/epc/playground/src/presets/PresetManagerUseCases.cpp
projects/epc/playground/src/presets/PresetManagerUseCases.h
projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankEditButtonMenu.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankEditButtonMenu.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankNameLabel.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankNameLabel.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetList.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetList.h
projects/epc/playground/src/serialization/PresetManagerMetadataSerializer.cpp
projects/epc/playground/src/testing/unit-tests/PresetManagerTests.cpp
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/dataModel/presetManager/Bank.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/dataModel/presetManager/BankUpdater.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/dataModel/presetManager/PresetManagerUpdater.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/PresetManagerPresenter.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/Bank.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/Header.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/Updater.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/BankContextMenu.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/BankTitle.java

feature is usable but not design complete
see #2363

Issue 2284

---

build-tools/create-c15-update/update_scripts/run.sh

Was not aware that 'ln' would link to non existent files.

added file check before linking to updates

---

projects/epc/playground/src/parameters/ModulateableParameter.h
projects/epc/playground/src/parameters/SplitPointParameter.cpp
projects/epc/playground/src/parameters/SplitPointParameter.h

Reverts nonlinear-labs-dev/C15#2397

Revert "closes #2391"

---

projects/epc/playground/src/device-settings/SplitPointSyncParameters.cpp
projects/epc/playground/src/device-settings/SplitPointSyncParameters.h
projects/epc/playground/src/presets/EditBuffer.cpp
projects/epc/playground/src/presets/EditBuffer.h

closes #2390

---

projects/epc/playground/src/parameters/names/ParameterDB.cpp
projects/epc/playground/src/parameters/names/ParameterDB.h
projects/epc/playground/src/presets/PresetParameterGroup.cpp

The currently loaded edit buffer does not guarantee to

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.h

closes #2416,
removed unnecessary call to setup of PresetListControl

fixes 2416

---

projects/epc/audio-engine/src/synth/C15Synth.cpp

added check if send channel is -1

issue 2472

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SplitPointsKeyBedEditor.java

split buttons are now stacked vertically

fixes #2437

---

projects/epc/playground/src/presets/EditBuffer.cpp
projects/epc/playground/src/proxies/hwui/HWUI.cpp
projects/epc/playground/src/proxies/hwui/HWUI.h

closes #2498

---

projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/items/InitSound.cpp

fixes #2499 -> init part was not called

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/PresetManagerContextMenu.java

removed 'export bank as file' context-menu-item from background context-menu

fixes #2500

---

projects/bbb/midi-over-ip/src/IO.cpp
projects/epc/playground/src/device-settings/ScreenSaverTimeoutSetting.cpp
projects/epc/playground/src/device-settings/ScreenSaverTimeoutSetting.h
projects/epc/playground/src/proxies/hwui/OLEDProxy.cpp
projects/epc/playground/src/proxies/hwui/OLEDProxy.h
projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnit.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnit.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/BOLED.cpp

added continous onLayoutInstalled Signal to OLEDProxy, screensaver timeout will now reset everytime an new layout is installed,

closes #2501

---

projects/epc/audio-engine/src/synth/C15Synth.cpp
projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
projects/epc/audio-engine/src/synth/c15-audio-engine/voice_allocation.h
projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
projects/epc/audio-engine/src/synth/input/InputEventStage.h
projects/epc/audio-engine/src/synth/input/TCDDecoder.cpp
projects/epc/audio-engine/src/synth/input/TCDDecoder.h

Issue 2495 extended

---

projects/bbb/bridge/CMakeLists.txt
projects/bbb/bridge/systemd/redirect-oled-websocket.service.in
projects/epc/playground/src/proxies/hwui/FrameBuffer.cpp
projects/epc/web-ui/CMakeLists.txt
projects/epc/web-ui/src/main/webapp/NonMaps.js.in
projects/shared/nltools/include/nltools/messaging/WebSocketJsonAPI.cpp
projects/shared/nltools/include/nltools/messaging/WebSocketJsonAPI.h

prevent sending oled updates while othe update is in flight

add bbb service to redirect oled websocket stream to ePC

---

projects/epc/audio-engine/CMakeLists.txt
projects/epc/audio-engine/src/io/RingBuffer.h
projects/epc/audio-engine/src/synth/C15Synth.cpp
projects/epc/audio-engine/src/synth/c15-audio-engine/ParallelData.h

fix usage of ARM Neon extensions

---

projects/epc/audio-engine/src/synth/C15Synth.cpp
projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
projects/epc/audio-engine/src/synth/c15-audio-engine/parameter_handle.h
projects/epc/audio-engine/src/synth/c15-audio-engine/pe_exponentiator.cpp
projects/epc/audio-engine/src/synth/c15-audio-engine/pe_exponentiator.h
projects/shared/nltools/include/nltools/threading/ContextBoundMessageQueue.h
projects/shared/nltools/src/nltools/system/AsyncCommandLine.cpp
projects/shared/nltools/src/nltools/threading/ContextBoundMessageQueue.cpp

I found some out-of-bound array accesses and potential optimizations. The out-of-bounds triggered some segfaults in my artificial test cases, not sure if this correlate with the crashes found by our users.

Release 21 07 debug

---

projects/epc/playground/src/http/ServedJournal.cpp

fix retrieving the system journal

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/MenuEditor.cpp

Made setup items wider, MIDI Mappings are now displaying fine

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp

BOLED: moved midi settings one position up in setup

---

projects/epc/audio-engine/src/recorder/FlacFrameStorage.cpp
projects/epc/audio-engine/src/recorder/FlacFrameStorage.h
projects/epc/audio-engine/src/recorder/Recorder.cpp
projects/epc/audio-engine/src/recorder/RecorderInput.cpp
projects/epc/audio-engine/src/recorder/RecorderInput.h
projects/epc/audio-engine/src/recorder/RecorderOutput.cpp
projects/epc/web-ui/recorder/bars.ts
projects/epc/web-ui/recorder/c15-proxy.ts
projects/epc/web-ui/recorder/scrollbar.ts
projects/epc/web-ui/recorder/update-stream.ts
projects/epc/web-ui/recorder/waveform.ts

Issue 2585

---

projects/epc/audio-engine/src/recorder/Recorder.cpp
projects/epc/audio-engine/src/recorder/Recorder.h
projects/epc/audio-engine/src/recorder/RecorderInput.cpp
projects/epc/audio-engine/src/recorder/RecorderInput.h
projects/epc/playground/src/device-settings/Settings.cpp
projects/epc/playground/src/device-settings/flac/AutoStartRecorderSetting.cpp
projects/epc/playground/src/device-settings/flac/AutoStartRecorderSetting.h
projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp
projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/dataModel/setup/SetupModel.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/dataModel/setup/SetupUpdater.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/MidiSettings.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/MidiSettingsProvider.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/useCases/SystemSettings.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/Belt.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/menu/GlobalMenu.java
projects/epc/web-ui/src/main/webapp/style.css
projects/shared/nltools/include/nltools/messaging/Message.h
projects/shared/nltools/include/nltools/messaging/Messaging.h

and new FLAC/Recorder setting page and entry in setup-menu, Enabling this Setting will also start the recorder if disabled, but disabling the setting will not stop the recording as i would see that behavior as not intuitive
closes #2592 
closes #2593

added auto start recorder setting

---

projects/epc/web-ui/recorder/waveform.ts

only show preset log entries for available audio

---

projects/epc/playground/src/proxies/hwui/base-unit/soled/BanksLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankNameLabel.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankNameLabel.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetListHeader.cpp
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/Header.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/Label.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/BankTitle.java

Issue 2597

---

projects/epc/acceptance-tests/src/Performance.cpp
projects/epc/acceptance-tests/src/mock/InputEventStageTester.cpp
projects/epc/acceptance-tests/src/mock/InputEventStageTester.h
projects/epc/audio-engine/src/MidiRuntimeOptions.cpp
projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
projects/epc/audio-engine/src/synth/input/InputEventStage.h

Issue 2614

---

projects/epc/playground/src/device-settings/ScreenSaverTimeoutSetting.cpp
projects/epc/playground/src/device-settings/ScreenSaverTimeoutSetting.h
projects/epc/playground/src/device-settings/SyncVoiceGroupsAcrossUIS.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/ScreenSaverTimeControls.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/ScreenSaverTimeControls.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp

fixed display issues for sync parts across uis and screensaver timeout  -> now other options are displayed aswell
changed defaults for sync parts across uis -> ON
changed defaults for ScreenSaver Timeout -> 5 Minutes
closes #2641

issue 2641

---

projects/epc/web-ui/recorder/styles.css
projects/epc/web-ui/recorder/waveform.ts

changed zoom buttons to be disabled at max and min zoom levels. maximal zoom goes to roughly 8h of audio

closes #2630

---

projects/epc/playground/src/device-settings/SettingsActions.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp
projects/epc/playground/src/use-cases/SettingsUseCases.cpp
projects/epc/playground/src/use-cases/SettingsUseCases.h
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/useCases/SystemSettings.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml

added reset to default options for 'classic' and 'high-res' midi

---

projects/epc/audio-engine/src/recorder/Recorder.cpp
projects/epc/audio-engine/src/recorder/RecorderOutput.cpp
projects/epc/web-ui/recorder/c15-proxy.ts
projects/epc/web-ui/recorder/playback-range.ts
projects/epc/web-ui/recorder/ui.ts

reset play position and selected range on reset

---

projects/playcontroller/firmware/src/main/src/tcd/nl_tcd_adc_work.c

Playcontroller, Bender: Send final values only if they have changed.
Closing #2384

Issue 2384

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp

added RAM label to system-info

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetListBase.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetListHeader.cpp

closes #2562

---

projects/epc/web-ui/recorder/c15-proxy.ts
projects/epc/web-ui/recorder/index.html
projects/epc/web-ui/recorder/styles.css
projects/epc/web-ui/recorder/ui.ts

TODO: rethink css of the prompt
currently it looks like this:

Issue 2623

---

projects/epc/web-ui/recorder/styles.css

add paddings and margin here and there

use css flex layout instead of transform

---

projects/epc/web-ui/recorder/waveform.ts

Issue 2667

---

projects/epc/web-ui/recorder/CMakeLists.txt
projects/epc/web-ui/recorder/preset-log.ts
projects/epc/web-ui/recorder/scripts.ts
projects/epc/web-ui/recorder/tsconfig.json
projects/epc/web-ui/recorder/waveform.ts

so we have less hassle with accessing souces via http etc

sources can be embedded into source maps,

---

projects/epc/web-ui/recorder/index.html
projects/epc/web-ui/recorder/ui.ts

fixed shortcuts: z now loads preset at selected postion, added left/right nudge, added tooltips for action buttons, closes #2622

Recorder: Fix Shortcuts + add Tooltips

---

projects/epc/audio-engine/src/synth/input/InputEventStage.cpp

Decoupled Split Sound Part determination from Local Enabled setting, closes #2682

issue 2682

---

CMakeLists.txt
build-tools/bbb/CMakeLists.txt
build-tools/epc/createUpdate.sh
build-tools/epc2/create-update/createEPC2UpdateDockerCommands.sh
build-tools/playcontroller/CMakeLists.txt
projects/epc/playground/src/device-settings/SSID.cpp

use that option to respect dual wifi (epc2 and bbb)
with suffixed SSID for BBB

add TARGET_PLATFORM cmake option

---

projects/epc/audio-engine/src/recorder/RecorderOutput.cpp
projects/epc/web-ui/recorder/bar-range.ts
projects/epc/web-ui/recorder/c15-proxy.ts
projects/epc/web-ui/recorder/scrollbar.ts
projects/epc/web-ui/recorder/selected-range.ts
projects/epc/web-ui/recorder/ui.ts

add eye-candy for playposition update races

rename playback-range into bar-range

---

projects/epc/playground/src/device-settings/BooleanSetting.h
projects/epc/playground/src/device-settings/DirectLoadSetting.cpp
projects/epc/playground/src/device-settings/DirectLoadSetting.h
projects/epc/playground/src/device-settings/EpcWifi.cpp
projects/epc/playground/src/device-settings/SettingsActions.cpp
projects/epc/playground/src/proxies/hwui/base-unit/BaseUnitPresetsAndBanksMode.cpp
projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/GlobalEventSinkBroker.cpp
projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/PresetManagerEvents.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/BOLED.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/LoadModeMenu.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/LoadModeMenu.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/LoadToPartPresetList.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/LoadToPartPresetList.h
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/PartOriginAttributeTests.cpp
projects/epc/playground/src/use-cases/DirectLoadUseCases.cpp
projects/epc/playground/src/use-cases/DirectLoadUseCases.h
projects/epc/playground/src/use-cases/EditBufferUseCases.cpp
projects/epc/playground/src/use-cases/EditBufferUseCases.h
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/LoadToPartMode.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/integrationTests/OracleTests.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/settings/DeveloperSettings.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/Belt.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/LoadModeMenu.java

closes #2708
@hhoegelo let's talk!

Issue 2708

---

projects/epc/playground/src/parameters/SplitPointParameter.cpp
projects/epc/playground/src/parameters/SplitPointParameter.h

changed split-point behavior to only load factory defaults if not locked

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml
projects/epc/web-ui/src/main/webapp/NonMaps.css
projects/epc/web-ui/src/main/webapp/style.css

not the whole ticket yet: #2714

WebUI: changed HW-Source-Enable Radiobuttons to Checkboxes, minor Layout improvements

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp

moved all undo indicators to the same positon, and remove undo/lock/split inidcation in all edit modes

issue 2552

---

projects/epc/CMakeLists.txt

Fix: force target CPU architecture spec for epc/epc2 code compilation

---

projects/epc/audio-engine/src/synth/c15-audio-engine/ae_poly_section.cpp

removed time key trk key down/up discrepancy, fixes #2749

hotfix 2749

---

projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/WebSocketConnection.java
projects/epc/web-ui/src/main/webapp/NonMaps.css

changed z-index of disconnected dialog to appear over all open popups + add modal overlay for ssid-changed dialog

---

build-tools/epc/createUpdate.sh
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankEditButtonMenu.cpp

install needed packages not only in build overlay, but also in real update overlay so it will be copied to the EPC

closes #2757 

---

projects/epc/playground/src/parameters/RibbonParameter.cpp
projects/epc/playground/src/parameters/RibbonParameter.h
projects/epc/playground/src/testing/unit-tests/PedalModeReturnTests.cpp
projects/epc/playground/src/testing/unit-tests/parameters/RibbonReturnModeTests.cpp

Ribbon set to Return To Center: set HW Amt to 50%

---

projects/epc/playground/src/device-settings/Passphrase.cpp
projects/epc/playground/src/device-settings/Passphrase.h
projects/epc/playground/src/device-settings/SettingsActions.cpp
projects/epc/playground/src/proxies/hwui/TextEditUsageMode.cpp
projects/epc/playground/src/proxies/hwui/controls/Button.cpp
projects/epc/playground/src/proxies/hwui/controls/Button.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/RenameLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/RenameLayout.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/PassphraseEditor.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/PassphraseEditor.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/PassphraseRenameLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/PassphraseRenameLayout.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/PassphraseView.cpp
projects/epc/playground/src/use-cases/SettingsUseCases.cpp
projects/epc/playground/src/use-cases/SettingsUseCases.h
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/DeviceSettings.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/DeviceSettingsProvider.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/useCases/SystemSettings.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml
projects/shared/nltools/include/nltools/messaging/Message.h

editable passphrase

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/RoutingsEditor.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml

Addresses the problems described in these comments: 
https://github.com/nonlinear-labs-dev/C15/issues/2714#issuecomment-904968733 
https://github.com/nonlinear-labs-dev/C15/issues/2714#issuecomment-905321140
a preview-build can be found here: https://we.tl/t-XYnyymQ9RP

Fix 2714 crash

---

projects/epc/playground/src/device-settings/Settings.cpp
projects/epc/playground/src/device-settings/midi/mappings/AftertouchCCMapping.h
projects/epc/playground/src/device-settings/midi/mappings/BenderCCMapping.cpp
projects/epc/playground/src/device-settings/midi/mappings/BenderCCMapping.h
projects/epc/playground/src/device-settings/midi/mappings/MappingSetting.cpp
projects/epc/playground/src/device-settings/midi/mappings/MappingSetting.h
projects/epc/playground/src/device-settings/midi/mappings/PedalCCMapping.h
projects/epc/playground/src/device-settings/midi/mappings/RibbonCCMapping.h
projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/RoutingsView.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/RoutingsView.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/MidiSettings.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml

MIDI Mapping fixups

---

projects/epc/playground/src/Application.cpp
projects/epc/playground/src/Application.h
projects/epc/playground/src/http/ContentManager.cpp
projects/epc/playground/src/http/ContentManager.h
projects/epc/playground/src/http/ContentSection.cpp
projects/epc/playground/src/http/RPCActionManager.cpp
projects/epc/playground/src/http/SectionAndActionManager.cpp
projects/epc/playground/src/http/SectionAndActionManager.h
projects/epc/playground/src/http/WebUISupport.cpp
projects/epc/playground/src/http/WebUISupport.h
projects/epc/playground/src/presets/BankActions.cpp
projects/epc/playground/src/presets/BankActions.h
projects/epc/playground/src/presets/EditBufferActions.cpp
projects/epc/playground/src/presets/EditBufferActions.h
projects/epc/playground/src/presets/PresetManager.cpp
projects/epc/playground/src/presets/PresetManager.h
projects/epc/playground/src/presets/PresetManagerActions.cpp
projects/epc/playground/src/presets/PresetManagerActions.h
projects/epc/playground/src/proxies/hwui/HWUIActions.cpp
projects/epc/playground/src/proxies/hwui/HWUIActions.h
projects/epc/playground/src/use-cases/ActionManagers.cpp
projects/epc/playground/src/use-cases/ActionManagers.h
projects/epc/web-ui/recorder/c15-proxy.ts
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/integrationTests/OracleTests.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/settings/DownloadEditBufferAsText.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/settings/OpenEditBufferAsText.java
projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/BankContextMenu.java

WebUI: Synchronization Issues fixed 

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/SplashLayout.cpp

end and reschedule Screensaver on Splashscreen (write/read BackupScreen) start and update

closes #2814 

---

.gitignore
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml

issue #2801

---

projects/epc/playground/src/presets/PresetManager.cpp

closes #2847

---

projects/epc/playground/src/presets/Bank.cpp
projects/epc/playground/src/presets/Bank.h
projects/epc/playground/src/presets/BankActions.cpp
projects/epc/playground/src/presets/EditBuffer.cpp
projects/epc/playground/src/presets/PresetManagerActions.cpp
projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/EditBankInfoLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/EditPresetInfoLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/RenameBankLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/AppendOverwriteInsertButtonMenu.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankAndPresetNumberLabel.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankEditButtonMenu.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetEditButtonMenu.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetList.cpp
projects/epc/playground/src/testing/TestHelper.h
projects/epc/playground/src/testing/unit-tests/EditBufferTests.cpp
projects/epc/playground/src/testing/unit-tests/PresetManagerTests.cpp
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/PartLabelSurviveStore.cpp
projects/epc/playground/src/testing/unit-tests/issues/Issue2828.cpp
projects/epc/playground/src/testing/unit-tests/mock/MockPresetStorage.cpp
projects/epc/playground/src/testing/unit-tests/parameters/SplitPointTests.cpp
projects/epc/playground/src/testing/unit-tests/presets/SendEditBufferTests.cpp
projects/epc/playground/src/use-cases/BankUseCases.cpp
projects/epc/playground/src/use-cases/BankUseCases.h
projects/epc/playground/src/use-cases/PresetManagerUseCases.cpp
projects/epc/playground/src/use-cases/PresetManagerUseCases.h
projects/epc/playground/src/use-cases/PresetUseCases.cpp
projects/epc/playground/src/use-cases/PresetUseCases.h
projects/epc/playground/src/use-cases/StoreUseCaseHelper.cpp
projects/epc/playground/src/use-cases/StoreUseCaseHelper.h

closes #2828
added missing calls to `updateLastLoadedPreset` on store operations

Issue 2828

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/dataModel/setup/DeviceInfoUpdater.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java

formatting and change shortcut links to be the same as global-menu links, closes #2860

issue #2860 -> Recorder, MC-View would not open via shortcuts

---

projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp

removed check that bank is selected before sending selected preset as ProgramChange, closes #2883

issue 2883

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp

moved channels in right order

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/AppendOverwriteInsertButtonMenu.cpp

added animatePreset after append

---

projects/epc/playground/src/parameters/HardwareSourceSendParameter.cpp
projects/epc/playground/src/parameters/HardwareSourceSendParameter.h
projects/epc/playground/src/proxies/hwui/controls/DotSlider.cpp
projects/epc/playground/src/proxies/hwui/controls/SelectedParameterValue.cpp
projects/epc/playground/src/proxies/hwui/controls/SelectedParameterValue.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/PlayControlParameterLayouts.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterEditButtonMenu.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterNameLabel.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterNameLabel.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/PhysicalControlSlider.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/PhysicalControlSlider.h
projects/epc/playground/src/testing/unit-tests/data/StringToolsTests.cpp
projects/shared/nltools/include/nltools/StringTools.h
projects/shared/nltools/src/nltools/StringTools.cpp

cleanup HW Layouts

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/useCases/AnimationManager.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/BankControl.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/BeltPreset.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/PresetList.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/StorePreset.java

does not fix 2982 but rather fixes #2968, I got the numbers mixed up

added overwrite animation for belt preset overwrite, closes #2982

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/PlayControls/SourcesAndAmounts/Sources/HardwareSourcesCol1.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/PlayControls/SourcesAndAmounts/Sources/PhysicalControlSendParameter.java

added doFirstLayoutPass if we want to set position of send control according to sibling parameter -> sibling gets layouted and then we copy the rect instead of copying the old rect

issue 2977

---

projects/epc/playground/src/groups/HardwareSourcesGroup.cpp
projects/epc/playground/src/groups/HardwareSourcesGroup.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/PlayControlParameterLayouts.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/PlayControlParameterLayouts.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ModulationRoutersCarousel.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ModulationRoutersCarousel.h
projects/epc/playground/src/testing/TestHelper.h
projects/epc/playground/src/testing/unit-tests/messaging/MessagingTests.cpp
projects/epc/playground/src/testing/unit-tests/presets/SendEditBufferTests.cpp

Issue 3013

---

build-tools/epc2/create-update/createEPC2UpdateDockerCommands.sh
projects/epc/audio-engine/system/audio-engine.service.in

Closes #3019 
Tested as an update. Looks good, I would say!

Issue-3019

---

projects/bbb/scripts/byebye-screen.sh.in

Issue-3007

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterEditButtonMenu.cpp

changed Edit Button Menu texts for Send/Receive HW Source selection

---

projects/epc/playground/src/proxies/hwui/controls/SelectedParameterValue.cpp
projects/epc/playground/src/proxies/hwui/controls/SelectedParameterValue.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/PlayControlParameterLayouts.cpp

BOLED: removed HW-Source arrow, moved CC Label, truncate display String for Channel Pressure to Ch. Press.

---

projects/epc/playground/src/presets/BankActions.cpp

change insert preset behaviour to open rename screen if modified

---

build-tools/CMakeLists.txt

issue-3062: Add missing cmake dependencies

---

projects/playcontroller/firmware/src/main/src/tcd/nl_tcd_adc_work.c
projects/playcontroller/firmware/src/shared/sys/nl_version.h

Poll hw sources #3051

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/PlayControls/SourcesAndAmounts/Sources/PhysicalControlSendParameter.java

local off parameters now show/hide more consistently

---

projects/epc/playground/src/use-cases/PresetManagerUseCases.cpp

added guessName to create-new-bank-from-editbuffer if the editbuffer was modified

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/PresetList.java

added fix for preset selection code to be rerun even if the selection did not change

WebUI: Autoscroll issue 3015

---

projects/epc/playground/src/parameters/ParameterImportConversions.cpp

added mc-amount converter for Unison_Detune

---

projects/epc/playground/src/groups/EnvelopeAGroup.cpp
projects/epc/playground/src/groups/EnvelopeBGroup.cpp
projects/epc/playground/src/groups/EnvelopeCGroup.cpp
projects/epc/playground/src/groups/FBMixerGroup.cpp
projects/epc/playground/src/groups/MonoGroup.cpp
projects/epc/playground/src/groups/OutputMixerGroup.cpp
projects/epc/playground/src/groups/SVFilterGroup.cpp
projects/epc/playground/src/parameters/scale-converters/KeyScaleConverter.cpp

changed order of parameter declarations to match order of parameter-list

fixup wrong scalings for parameters

---

projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/UnmodulatebaleParameterLayouts.cpp
projects/epc/playground/src/testing/unit-tests/PresetMessageTests.cpp
projects/shared/nltools/include/nltools/messaging/Message.h

closes #3184
fixes scale-recall

Issue fix scale recall + minor bug fix: scale layout reset button

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/CombFilter/CombFilterCol2.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulationSourceKeytracking.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulationSourceSwitch.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/MonoAndUnison/MonoColumn.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/OscA/FluctColumn.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/OscA/PitchColumn.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/OscB/PitchColumn.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/UnmodulateableNumericDisplay.java

WebUI: Issue 3164

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulatableHorizontalSlider.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulationSourceHighPriority.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulationSourceLabel.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/NumericalControlLarge.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/SmallKnobParameter.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/SmallModulateableParameter.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ValueDisplayLarge.java

... and fix some minor clipping issues for small modulateable parameter instances
closes #3167

WebUI: always show mc-indication

---

projects/epc/playground/src/parameters/Parameter.cpp
projects/epc/playground/src/parameters/Parameter.h
projects/epc/playground/src/proxies/hwui/HWUI.cpp
projects/epc/playground/src/proxies/hwui/HWUI.h
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/presenters/ParameterPresenter.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/presenters/ParameterPresenterProvider.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java

added suppression of fine state for parameters where fine and coarse denominators are the same
closes #2891

closes #2891

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetList.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetList.h
projects/epc/playground/src/use-cases/BankUseCases.cpp
projects/epc/playground/src/use-cases/BankUseCases.h

added shift modifier for Preset Navigation in the HWUI PresetList. Shift + Inc Dec will select the first/last preset in the current Bank
closes #2886

closes #2886

---

projects/bbb/bridge/src/FileSystemSync.cpp
projects/bbb/bridge/src/io/UpdateService.cpp
projects/epc/acceptance-tests/src/MIDI/HWSourceEnableTests.cpp
projects/epc/playground/src/device-settings/SettingsActions.cpp
projects/epc/playground/src/playground-helpers.cpp
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/dataModel/editBuffer/EditBufferModelUpdater.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/integrationTests/OracleTests.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/integrationTests/TestWithSteps.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/presenters/ParameterPresenterProvider.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/Parameter.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/Bank.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/Header.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/Tape.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/Updater.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/ParameterInfoDialog.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/undo/UndoTreeWindow.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/pointer/TouchClick.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/pointer/TouchPinchStart.java

made the webUI and Playground shut up about old logs that no one cares about anymore
closes #3022

remove logs: 3022

---

projects/web/static/online-help/_menu.html
projects/web/static/online-help/documents/_content.html
projects/web/static/online-help/documents/change-log/22-18.html
projects/web/static/online-help/documents/change-log/index.html

22-18 - updated Documentation

---

projects/epc/playground/src/proxies/hwui/FourStateLED.cpp
projects/epc/playground/src/proxies/hwui/FourStateLED.h

added throttler to FourStateLed::syncHWUI led
closes #3214

prevent blinking LEDs on undo/redo traversal

---

build-tools/bbb/Dockerfile
build-tools/build-container/Dockerfile.in
build-tools/epc/Dockerfile
build-tools/epc/createUpdate.sh
build-tools/epc2/collect-packages/BaseDockerfile
build-tools/epc2/create-update/Dockerfile
build-tools/epc2/create-update/createUpdate.sh
build-tools/playcontroller/Dockerfile
projects/shared/configuration/CMakeLists.txt
projects/shared/configuration/lib/build.ts
projects/shared/configuration/package.json
projects/shared/configuration/process.sh
projects/shared/configuration/tsconfig.json

update that can be tested: https://we.tl/t-FlovTr6fSo

Use-new yaml-param-DB fix build-update

---

projects/shared/configuration/CMakeLists.txt
projects/shared/configuration/lib/build.ts

Configuration - corrections

---

projects/epc/audio-engine/src/synth/c15-audio-engine/ae_poly_section.cpp

Issue 3317

---

projects/epc/playground/resources/free-diskspace-information.sh
projects/epc/playground/src/device-info/FreeDiscSpaceInformation.cpp

Issue 3313

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/BeltParameterLayout.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/FineButton.java

issue 3267

---

projects/epc/playground/src/presets/EditBuffer.cpp
projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/GlobalEventSinkBroker.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankButton.cpp
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Conversion/ConvertDualToDualSoundTests.cpp
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadDualPresetPartIntoLayerSoundTests.cpp
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadDualPresetPartIntoSplitSoundTests.cpp
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadSingleToLayerSoundTests.cpp
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadSingleToSplitSoundTests.cpp
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/PartOriginAttributeTests.cpp
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/UnselectDiabledParameterOnSoundTypeChange.cpp
projects/epc/playground/src/testing/unit-tests/issues/Issue3305.cpp
projects/epc/playground/src/use-cases/VoiceGroupAndLoadToPartManager.cpp
projects/epc/playground/src/use-cases/VoiceGroupAndLoadToPartManager.h
projects/epc/playground/src/use-cases/VoiceGroupUseCases.cpp
projects/epc/playground/src/use-cases/VoiceGroupUseCases.h

reintroduced toggleVoiceGroup but silent, we don't want to explicitly select a new parameter (nor show its layout) if we change the voicegroup from a focus like SoundLayout or PresetLayout, closes #3305

issue 3305

---

projects/epc/playground/src/proxies/playcontroller/PlaycontrollerProxy.cpp
projects/playcontroller/firmware/src/main/src/tcd/nl_tcd_adc_work.c

fix ribbon rtc + relative first touch position

Issue 3287

---

projects/epc/playground/src/parameters/scale-converters/LinearBipolar100PercentScaleConverter.cpp
projects/shared/nltools/CMakeLists.txt

This reverts commit 35f07258fd9a7eb7b1c8f99e4ddd6bf45477bd8b.

revert make NLtools dependend on yaml-configuration

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableParameterLayouts.cpp

remove copyFrom for ModulateableParameterLayouts

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ScaleParameterLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterCarousel.cpp

update visual of scale parameter carousel, closes #3298

---

projects/playcontroller/firmware/src/main/src/tcd/nl_tcd_adc_work.c

nl_tcd_adc_work.c:  fix ribbon relative factor application
fixes #3367

issue 3367

---

projects/shared/configuration/src/definitions/GapFilter.yaml

fix typo in Long-Label for Gap-Balance

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/PresetContextMenu.java

removed check for disabled preset-drag-drop to allow multiple preset selection even if the setting is disabled, closes #3378

closes #3378

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp
projects/epc/playground/src/use-cases/SettingsUseCases.cpp
projects/epc/playground/src/use-cases/SettingsUseCases.h

added screensaver reset in Setup-Navigation

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/CombFilter/CombFilterCol2.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/ModulateableNumericalControl.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/PlayControls/MacroControls/MacroControlParameter.java

fixup macro-slider scaling, closes #3361

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/LoadPreset.java

added check for Converted and Init uuids to enable load preset button when applicable, closes #3327

closes #3327

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/Preset.java

closes #3379

---

projects/epc/acceptance-tests/src/MIDI/PedalTests.cpp
projects/epc/audio-engine/src/synth/input/InputEventStage.cpp

Issue 3319

---

projects/web/static/nonmaps/src/main/webapp/NonMaps.css

removed blue overlay for generic button hover states, replace with explicit css for close buttons
closes #3275

Issue 3275

---

projects/bbb/midi-over-ip/src/IO.cpp
projects/epc/audio-engine/src/io/midi/AlsaMidiInput.cpp

The implemented handling off poll result was just
wrong, as it compared the 'number of evented file handles or errno' with 'poll event type'. This used to work, but only accidentally.
Now, we throw on every possible error (EFAULT, EINTR, EINVAL, ENOMEM) as there is nothing we could do to fix if any of them is returned.
OTOT, a small refactoring is applied to MidiBridge IO::fetchChunk as the 'magic' "+1" should be used a local as possible.

Fix poll return value handling

---

projects/shared/configuration/readme.md

updated readme.md to better clarify required node versions
_(building within a fresh environment will hopefully stop to cause tsc troubles)_

configuration: better node version description

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/EditMCInfoLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulationRouterParameterLayouts.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulationRouterParameterLayouts.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/RenameMCLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MacroControlEditButtonMenu.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MacroControlEditButtonMenu.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterEditButtonMenu.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterEditButtonMenu.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SelectedMacroControlsHWSourceValue.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SelectedMacroControlsHWSourceValue.h

implement mod-router-edit-layout to behave and act like the mc-layout eventhough the selected parameter is still the mod-router/hw-amt
closes #3427

fixup issue 3427

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetTypeLabel.cpp
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/presets/TypeLabel.java

Issue 3456

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetInfoContent.cpp

added color-tag to hwui preset-info, closes #3426

---

projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferEvents.cpp

fixup rules for FX-FB arrows for FX-II in split sounds

---

projects/epc/playground/src/presets/EditBuffer.cpp
projects/epc/playground/src/presets/EditBuffer.h
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Conversion/ConvertDualToSingleSoundTests.cpp
projects/epc/playground/src/testing/unit-tests/issues/Issue2995/ConvertTests.cpp
projects/epc/playground/src/testing/unit-tests/issues/Issue2995/LoadToPartTests.cpp

Issue 3473: convert rules for FX_From and To_FX (Invert on Convert VG-II and load-to-part from Single-II)

---

projects/epc/playground/resources/templates/init-screen/dual-init-screen.json
projects/epc/playground/resources/templates/init-screen/single-init-screen.json
projects/epc/playground/src/proxies/hwui/descriptive-layouts/ConditionRegistry.cpp
projects/epc/playground/src/proxies/hwui/descriptive-layouts/TemplateEnums.h
projects/epc/playground/src/proxies/hwui/descriptive-layouts/conditions/SoundConditions.cpp
projects/epc/playground/src/proxies/hwui/descriptive-layouts/conditions/SoundConditions.h

removed init-part from init-single-sound-screen

---

projects/epc/playground/resources/templates/init-screen/dual-init-screen.json
projects/epc/playground/resources/templates/init-screen/single-init-screen.json
projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/SingleSoundEditMenu.cpp

BOLED: moved order of sound-types in convert menus in 

---

projects/epc/playground/src/presets/EditBuffer.cpp
projects/epc/playground/src/presets/EditBuffer.h
projects/epc/playground/src/testing/unit-tests/issues/Issue2995/ConvertTests.cpp
projects/epc/playground/src/testing/unit-tests/mock/MockPresetStorage.cpp

added test-case for faulty usecase, closes #3506

fixup ruleset for part-volume-fx-mix conversion rules

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java

fixup parameter edit in non-maps, closes #3533

---

projects/epc/playground/src/parameters/ScopedLock.cpp
projects/epc/playground/src/parameters/ScopedLock.h
projects/epc/playground/src/presets/EditBuffer.cpp
projects/epc/playground/src/presets/EditBuffer.h
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadDualPresetPartIntoLayerSoundTests.cpp
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadDualPresetPartIntoSplitSoundTests.cpp
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadSingleToLayerSoundTests.cpp
projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadSingleToSplitSoundTests.cpp
projects/epc/playground/src/testing/unit-tests/issues/Issue2995/LoadToPartTests.cpp
projects/epc/playground/src/testing/unit-tests/issues/Issue3497.cpp

implement more load-to-part rules according to #3497 
closes #3497

Issue 3497

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/presenters/EditBufferPresenter.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/presenters/EditBufferPresenterProvider.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/Overlay.java

proposed new set of rules to prevent FX-Disabled display if Fx-FB is used

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankButton.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankButton.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/LoadModeMenu.cpp

change softbuttons 1&4 to be consistent and no longer obstruct store/…edit indications, closes #3542

boled: presetmanager-layout buttons 

---

projects/shared/configuration/src/definitions/EnvelopeC.yaml

yaml: added inactive position for Envelope C - Loop

---

projects/epc/playground/src/parameters/value/QuantizedValue.cpp
projects/epc/playground/src/parameters/value/QuantizedValue.h
projects/epc/playground/src/testing/unit-tests/parameters/ModulatedParameterTests.cpp
projects/epc/playground/src/use-cases/ModParameterUseCases.cpp
projects/web/static/nonmaps/src/test/java/com/nonlinearlabs/client/NonMapsTest.java

use that fixed method for inc/dec mod limits

fix QuantizedValue::getNextStepValue for passed values

---

projects/epc/playground/src/device-info/AftertouchCalibratedStatus.h
projects/web/client/nonmaps-preset-search/search-result-preset.ts
projects/web/client/nonmaps-preset-search/search.html
projects/web/client/nonmaps-preset-search/search.less
projects/web/client/nonmaps-preset-search/search.ts
projects/web/client/nonmaps-preset-search/shared-state.ts
projects/web/client/playground-proxy.ts
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/NonMaps.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/preset/Preset.java

Issue 3428

---

projects/web/client/nonmaps-preset-search/search.ts

Preset_Search: also show bank-arrows for last bank

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/FX_II_Indicator.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/FX_I_Indicator.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/LayerSoundLayout.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SoundLayout.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SplitSoundLayout.java

WebUI: added clickable FX-indicators in Sound-Belt Layout

---

projects/epc/audio-engine/src/main.cpp
projects/epc/playground/src/device-info/BufferUnderruns.cpp
projects/epc/playground/src/device-info/BufferUnderruns.h
projects/shared/nltools/include/nltools/messaging/Message.h

added periods information to BufferUnderrun message

---

projects/shared/configuration/src/definitions/EnvelopeC.yaml

fixed Env C Loop info typo

---

projects/epc/playground/src/device-info/DeviceInformation.h
projects/epc/playground/src/device-settings/Settings.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/BOLED.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/BOLED.h
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.h

closes #3616 by rebuilding the setup focus when the aftertouch-calibration-status changed

Issue 3616

---

projects/epc/playground/src/device-settings/BaseUnitUIDetail.cpp
projects/epc/playground/src/device-settings/BaseUnitUIDetail.h
projects/epc/playground/src/device-settings/Settings.cpp
projects/epc/playground/src/proxies/hwui/base-unit/BaseUnitPlayMode.cpp
projects/epc/playground/src/proxies/hwui/base-unit/BaseUnitPlayMode.h
projects/epc/playground/src/proxies/hwui/base-unit/soled/EditModeLayout.cpp
projects/epc/playground/src/proxies/hwui/base-unit/soled/LastTouchedRibbonLabel.cpp
projects/epc/playground/src/proxies/hwui/base-unit/soled/LastTouchedRibbonLabel.h
projects/epc/playground/src/proxies/hwui/base-unit/soled/ParamEditModeRibbonBehaviourLabel.cpp
projects/epc/playground/src/proxies/hwui/base-unit/soled/PlayModeLayout.cpp
projects/epc/playground/src/proxies/hwui/base-unit/soled/PlayModeLayout.h
projects/epc/playground/src/proxies/hwui/base-unit/soled/PlayOrEditModeLayout.cpp
projects/epc/playground/src/proxies/hwui/base-unit/soled/PlayOrEditModeLayout.h
projects/epc/playground/src/proxies/hwui/base-unit/soled/RibbonLabel.cpp
projects/epc/playground/src/proxies/hwui/base-unit/soled/RibbonModeLabel.cpp
projects/epc/playground/src/proxies/hwui/base-unit/soled/RibbonModeLabel.h
projects/epc/playground/src/proxies/playcontroller/PlaycontrollerProxy.cpp
projects/epc/playground/src/proxies/playcontroller/PlaycontrollerProxy.h
projects/epc/playground/src/use-cases/RibbonParameterUseCases.cpp
projects/epc/playground/src/use-cases/RibbonParameterUseCases.h

added new long/short press behaviour for FUNC button in Edit-or-Play mode, allows to toggle absolute and relative again, kinda closes #3509
a build which can be tested can be found here: https://we.tl/t-lzYaNLeqSl

HWUI: reintroduce relative/absolute toggle for ribbons

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/oleds/Oleds.ui.xml
projects/web/static/nonmaps/src/main/webapp/NonMaps.css

moved canvases into svg, added resize option to oled-dialog, closes #2893

WebUI: mirror-oleds resizeable

---

projects/epc/playground/src/parameters/ScopedLock.cpp
projects/epc/playground/src/parameters/ScopedLock.h
projects/epc/playground/src/presets/EditBuffer.cpp
projects/epc/playground/src/presets/EditBuffer.h
projects/epc/playground/src/presets/EditBufferConverter.cpp
projects/epc/playground/src/presets/EditBufferConverter.h
projects/epc/playground/src/presets/EditBufferModifierSharedBase.cpp
projects/epc/playground/src/presets/EditBufferModifierSharedBase.h
projects/epc/playground/src/presets/EditBufferToPartLoader.cpp
projects/epc/playground/src/presets/EditBufferToPartLoader.h
projects/epc/playground/src/testing/unit-tests/EditBufferTests.cpp
projects/epc/playground/src/use-cases/EditBufferUseCases.cpp

inital revision of extracted functionality from EditBuffer to EditBufferToPartLoader and EditBufferConverter to try to reduce the EditBuffer complexity and find shared methods

extract Conversion and LoadToPart functionality from EditBuffer into seperate classes

---

projects/epc/playground/resources/templates/sound/edit/SingleSoundEditLayout.json

HWUI: removed part label from single-sound-edit-menu

---

build-tools/create-c15-update/update_scripts/run.sh
projects/bbb/scripts/install-update-from-epc.sh.in
projects/bbb/scripts/install-update.sh.in

added move and sync before displaying a message that says that the C15 can be restarted. potential fix for (closes #3464)

update run.sh and install-update.sh to first rename the tar and then prompt reboot

---

projects/epc/playground/src/presets/EditBufferActions.cpp
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SoundSettingsButton.java

added copy-fx from VG into VG items to SoundEditMenus in WebUI-Belt, closes #3646

WebUI: added Copy-FX Item to SoundMenus

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/BeltParameterLayout.java

implemented same behaviour for doubleClick (setDefault) as in HWUI modulationCarousel
closes #3429

WebUI: add default actions for double-click -> mod-amt and mc-pos

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/MappedSvgImage.java

added missing requestLayout, as we called getPictureHeight inside some doLayout -> and dont relayout if the phase changed, closes #3648

WebUI: fixup missing serial-arrow

---

projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/PlayControlParameterLayouts.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/PlayControlParameterLayouts.h

renamed button from 'mode' to 'touch'

---

projects/epc/playground/src/parameters/MacroControlParameter.h
projects/epc/playground/src/presets/EditBuffer.cpp
projects/epc/playground/src/presets/EditBuffer.h
projects/epc/playground/src/presets/PresetManager.cpp

added explicit update of bound ribbons after the preset-manager was loaded, closes #3671

issue 3671

---

projects/epc/playground/src/parameters/scale-converters/LinearHerzScaleConverter.cpp
projects/epc/playground/src/parameters/scale-converters/dimension/TuneReferenceFrequencyDimension.cpp
projects/epc/playground/src/parameters/scale-converters/dimension/TuneReferenceFrequencyDimension.h
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml

fixup dimension display for tune reference webui and fixup step size for incremental (with arrow keys) steps, closes #3687

WebUI: fix dimension and step-size for Tune-Reference

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/FineButton.java

WebUI: added disable of fine-mode when shift is released

---

projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
projects/epc/playground/src/device-settings/TransitionTime.cpp
projects/epc/playground/src/parameters/scale-converters/EditSmoothingTimeMSScaleConverter.cpp
projects/shared/configuration/src/parameter_declarations.yaml
projects/shared/configuration/src/settings.yaml

changed TransitionTime to allow 0.0ms and change EditSmoothing to go up to 2000ms

issue 3672

---

projects/epc/audio-engine/src/MidiRuntimeOptions.cpp
projects/epc/audio-engine/src/MidiRuntimeOptions.h
projects/epc/audio-engine/src/io/RingBuffer.h
projects/epc/audio-engine/src/recorder/RecorderInput.h
projects/epc/audio-engine/src/recorder/RecorderOutput.h
projects/epc/audio-engine/src/synth/C15Synth.cpp
projects/epc/audio-engine/src/synth/C15Synth.h
projects/epc/audio-engine/src/synth/Synth.cpp
projects/epc/audio-engine/src/synth/Synth.h
projects/epc/audio-engine/tests/Recorder.cpp
projects/epc/playground/src/device-settings/SendActiveSensingSetting.cpp
projects/epc/playground/src/device-settings/SendActiveSensingSetting.h
projects/epc/playground/src/device-settings/Settings.cpp
projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp
projects/shared/configuration/src/settings.yaml
projects/shared/nltools/include/nltools/messaging/Message.h
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/dataModel/setup/SetupModel.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/dataModel/setup/SetupUpdater.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/presenters/DeviceSettings.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/presenters/DeviceSettingsProvider.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/useCases/SystemSettings.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.java
projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml

closes #3698 by queuing active-sensing messages every 250ms

Issue 3698

---

projects/epc/playground/src/parameters/ParameterFactory.cpp
projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/UnisonParameterCarousel.cpp

added missing explicit parameter-types (for unison)

---

projects/epc/audio-engine/src/synth/C15Synth.cpp
projects/epc/audio-engine/src/synth/C15Synth.h

added reschedule of active-sensing on midi-settings-message received

---

projects/web/static/online-help/src/_menu.html
projects/web/static/online-help/src/documents/_content.html
projects/web/static/online-help/src/documents/change-log/23-12.html
projects/web/static/online-help/src/documents/change-log/23-14.html

What's New 22-14

---

projects/epc/playground/src/proxies/hwui/HWUI.cpp
projects/epc/playground/src/proxies/hwui/HWUI.h

HWUI: reset 'fine' on all focus changes

---

projects/shared/configuration/src/definitions/StateVariableFilter.yaml

restored svf fm parameter info

SVF FM parameter Info correction

---

projects/web/static/online-help/src/_menu.html
projects/web/static/online-help/src/documents/_content.html
projects/web/static/online-help/src/documents/change-log/23-17.html
projects/web/static/online-help/src/documents/change-log/index.html

Whatsnew 23-17

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/settings/PopoutOleds.java
projects/web/static/nonmaps/src/main/webapp/mirror-oleds.html.in

added gray background to preserve color theme, move ui above the canvas, fixup cross-browser issues

WebUI: fixup and cleanup mirror-oleds tab

---

projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml

fixup sendActiveSensing radio-button styling

---

projects/web/static/online-help/src/_menu.html
projects/web/static/online-help/src/documents/_content.html
projects/web/static/online-help/src/documents/change-log/23-36.html
projects/web/static/online-help/src/documents/change-log/index.html

documented the changes in milestone-production-refinements, closes #3881

What's New 23-36

---

projects/playcontroller/tools/src/make-cal-bin.c

Remove zero or partiallly written outfile on exit

Fix make-cal-bin utility

---

projects/playcontroller/tools/src/make-cal-bin.c

Fix make-cal-bin utility (#3931)
