nonlinear-labs-dev/C15

- playground/src/tools/FileTools.h
- playground/src/xml/FileOutStream.cpp
GLib could throw an exception which was not caught. Resulting in a not responding UI. 
Fixed with catching the exception and ignoring said file.
> Fixed "Deadlocked" state if certain files were not readable when listing importable files

- playground/src/clipboard/Clipboard.cpp
Paste Preset now creates correctly named transaction
> fixed apparent typo

- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/StoreOptionsMenu.java
WebUI: Preset-Bauchbinde: Der Append/Insert/Overwrite-Button verschwindet manchmal, wenn man seinen Zustand im BOLED ändert.
> fixed the bug: 

- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/preset/Preset.java
moved selecting out of mouse down into click that a dragged preset mustn't be selected while being dragged, that helps with moving from one bank into a different bank in the belt
> is mustn't a word? Changed Click behaviour for presets in maps

- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/setup/AboutList.java
removed the broder around the text so that it appears more better and nicer for the eyes and the brain because that helps understand its not editable but read only
name says it all. pretty self explanatory
> feature-make-about-textinputfieldarea-different-color-because-it-is-not-allowed-to-be-edited-and-it-gives-a-wrong-impression-that-it-might-be

- playground/src/proxies/hwui/panel-unit/boled/preset-screens/PresetManagerLayout.cpp
- playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/AnyParameterLockedIndicator.cpp
The initial state of the locked-label should be invisible.
> the 'setup' call after setting focus and mode ist just useless.

- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/preset/Preset.java
- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/ContextMenuItem.java
- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/PresetContextMenuItem.java
- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BeltPreset.java
- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetColorTagContextMenu.java
- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetContextMenu.java
extracted isInContextMenu from isSelected to fix a bug that caused the belt preset list to jump to a nonselected preset, also finished the feature that clicking on any presetContextmenuItem closes the multiple Preset Selection
> Fixed Bug and finished Feature

- playground/src/proxies/hwui/HWUI.cpp
changed logic in HWUI to meet the 2 criteria: bank to Parameter -> remove Edit and Parameter to Store -> keep Store Focus
> Prameter to Store no longer "swallows" Store UIFocus

- NonMaps/src/com/nonlinearlabs/NonMaps/client/ServerProxy.java
- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Bank.java
- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/InsertTape.java
- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/DragProxy.java
- playground/src/presets/BankActions.cpp
- playground/src/presets/BankActions.h
- playground/src/presets/PresetBank.cpp
- playground/src/presets/PresetBank.h
We have a problem making this feature look good. Because we still snap to the (way too fine) grid, banks are in weird positions if clustered. That would call for a more sophisticated algorithm to determine the width and height of "InsertTapes".
> added functionality to insert bank in clusters

- playground/src/proxies/hwui/panel-unit/boled/setup/ExportBackupEditor.cpp
Changed resulting filename because std::fs::copy has a problem with any ':' in filename. 
removed Homegrown solution for moving file and replaced by std::filesystem
it copies and removes original file because it has to do work across different file systems.  
FIXES: #237
> Fix export

- NonMaps/CMakeLists.txt
- bbbb/CMakeLists.txt
- bbbb/systemd/bbbb.service.in
- build.sh
- playground/CMakeLists.txt
- playground/systemd/playground.service.in
Systemd services belong to the project and not to the build environment.
This adds all necessary changes in order to have *.service files installed
with the project. Also installation target nonlinear/playground is part
of the project, rather than set by a command line argument.
Removed some unnecessary whitespaces.
> Add systemd services as part of the project

- playground/src/presets/PresetManagerActions.cpp
- playground/src/proxies/hwui/panel-unit/boled/setup/ImportBackupEditor.cpp
to counter backup interchange problems I changed the name generation of webui-backups to include a sanitzed time string also changed boled backup filter to counter teh browser feature of adding a (1) or (2) to already downloaded files after .xml -> (.xml (1).tar.gz is a common file which is not found by boled backup) I believe that removing the .xml qualifier will not hurt the robustness of the feature but add more value to the user by easing the backup process
adresses both points made in #278
> Backup Proposals

- playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/LockedIndicator.h
- playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/AnyParameterLockedIndicator.cpp
- playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/AnyParameterLockedIndicator.h
Fixes: Presetmanager lock symbol not showing locksymbol if last selected parameter was not locked, but some parameter was locked.
> subscribed lockedindicator to locks changed signal

- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Bank.java
- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/Tape.java
I fixed the 'fangbereich' issue (#314), but also found some UI glitches with the insert tapes. 
When trying to fix it, I found the UI solution that I just implemented here. @schlenkibus , @nonlinear-labs , please comment on this suggestion - it is not only less code, it is IMHO also easier for the users to not divide between 'normal' and 'insert' tapes.
If you don't like it, I can easily revert it and only fix the fangbereich.
> streamlined visualization and code for insert tapes

- playground/src/presets/PresetBank.cpp
now it does not crash anymore -> which led to deleting the bank
(Still dont think that behavior is acceptable (deleteting a bank if a error occurs) but i left it in)
> fix preset file delete

- playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/AppendOverwriteInsertButtonMenu.cpp
- playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetListEntry.cpp
removed callback (on animation finish) in destructor of PresetListEntry, prevents crash if layout is changed and object is in destruction
currently the only purpose of animation and the whole system is to display the "Schulz-🚆" now the callback will not be called if preset list goes out of scope before / while the animation is playing -> also that would not be the thing we want, because it only gets destructed if we change the focus, manually setting the focus to preset-edit is unwanted 
#568
> Crash-Fix: removed doCallback in destructor of PresetListEntry 

- playground/src/libundo/undo/Scope.cpp
- playground/src/libundo/undo/Transaction.cpp
- playground/src/libundo/undo/Transaction.h
- playground/src/presets/PresetManager.cpp
- playground/src/presets/PresetManager.h
- playground/src/proxies/hwui/HWUI.cpp
Was used in "Write-document" to write all Undo Transactions.
Removed it with a Breadth-First algorithm that collects all child nodes while calling the callback on current node.
It is faster and does not crash at an tree size of around 66750 (on my machine) compared to the prior implementation.
Iterator Invalidation is not a problem as long as the vector does not change the order of elements.
I also played around with reserving the space needed but it was counter intuitive and made the runs slower that now.
Some Benchmarks:
Data from when recurse crashed until I felt like it was enough:
The other Changes in Transaction are clang-tidy Warnings that i fixed.
#565
> Removed Undo::Recurse

- playground/src/device-settings/WifiSetting.cpp
added compile-time branches in WiFi Setting to dissalow calling nonexistend services on Dev_PC's
> Cleanup WiFi Warnings on Development PC

- NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/ParameterCompareButton.java
- playground/src/parameters/Parameter.cpp
- playground/src/presets/EditBuffer.cpp
- playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
cleanup code paths in compare / recall for the case that no original preset exists -> init sound, now if no original preset exists the value with which current value is being compared is the default value. if no previous preset exists and editbuffer parameter is different than default -> current parameter changed
> Repaired Recall and Compare with Init-Sound

- playground/src/presets/Bank.cpp
at the place where it was needed, so default 'to_string' for enums
was utilised, turning the values into numbers.
The load code now tries to interpret the string as number and converts
it into a string afterwards. If it fails, it uses the string as is.
fixes #746
> overload to_string(Bank::AttachmentDirection dir) was unknown

- audio-engine/src/synth/c15-audio-engine/dsp_host.cpp
- audio-engine/src/synth/c15-audio-engine/pe_defines_config.h
cleaned up pe_defines_config.h by removing perf_measure defines, as they are now obsolete
> Dsp cleanup perf measure

- audio-engine/src/synth/c15-audio-engine/ae_soundgenerator.cpp
- audio-engine/src/synth/c15-audio-engine/dsp_host.cpp
- audio-engine/src/synth/c15-audio-engine/paramengine.cpp
- audio-engine/src/synth/c15-audio-engine/paramengine.h
- audio-engine/src/synth/c15-audio-engine/pe_defines_config.h
- audio-engine/src/synth/c15-audio-engine/pe_defines_params.h
removed defines and corresponding code for:
- test_key_update_pan
- test_fast_fold_asym
- test_flushModeFlag
- test_whichEnvelope
- test_phase_reset
(see on google drive: Nonlinear Labs > Linux Engine > Linux Engine 1.56 Status :: Review 1.56)
> removed redundant code according to Review 1.56

- audio-engine/src/synth/c15-audio-engine/paramengine.cpp
up to now, a short glitch was audible when releasing a key (and having a note shift != 0)
this fix should get rid of that glitch
> fixed keyUp glitch caused by hw_note_shift

- audio-engine/src/synth/c15-audio-engine/dsp_host.cpp
- audio-engine/src/synth/c15-audio-engine/paramengine.cpp
- audio-engine/src/synth/c15-audio-engine/paramengine.h
- audio-engine/src/synth/c15-audio-engine/pe_defines_config.h
- rendering can perform in two modes: by clockId or by direct param_body iteration (default)
- both modes produce pretty similar performance results, although the iterator seems to variate a little more
> parameter renderers now running continuously

- audio-engine/src/synth/c15-audio-engine/SignalStorage.h
- audio-engine/src/synth/c15-audio-engine/ae_cabinet.cpp
- audio-engine/src/synth/c15-audio-engine/ae_combfilter.cpp
- audio-engine/src/synth/c15-audio-engine/ae_echo.cpp
- audio-engine/src/synth/c15-audio-engine/ae_feedbackmixer.cpp
- audio-engine/src/synth/c15-audio-engine/ae_flanger.cpp
- audio-engine/src/synth/c15-audio-engine/ae_gapfilter.cpp
- audio-engine/src/synth/c15-audio-engine/ae_outputmixer.cpp
- audio-engine/src/synth/c15-audio-engine/ae_reverb.cpp
- audio-engine/src/synth/c15-audio-engine/ae_soundgenerator.cpp
- audio-engine/src/synth/c15-audio-engine/ae_svfilter.cpp
- audio-engine/src/synth/c15-audio-engine/ae_svfilter_fir.cpp
- audio-engine/src/synth/c15-audio-engine/ae_svfilter_proto.cpp
- audio-engine/src/synth/c15-audio-engine/dsp_defines_signallabels.h
- audio-engine/src/synth/c15-audio-engine/dsp_host.cpp
- audio-engine/src/synth/c15-audio-engine/dsp_host_examine.h
- audio-engine/src/synth/c15-audio-engine/paramengine.cpp
- audio-engine/src/synth/c15-audio-engine/paramengine.h
- audio-engine/src/synth/c15-audio-engine/pe_defines_labels.h
- audio-engine/src/synth/c15-audio-engine/pe_defines_lists.h
- audio-engine/src/synth/c15-audio-engine/pe_defines_params.h
- audio-engine/src/synth/c15-audio-engine/pe_defines_testconfig.h
- audio-engine/src/synth/c15-audio-engine/pe_utilities.h
- audio-engine/src/synth/c15-audio-engine/tcd_decoder.cpp
- audio-engine/src/synth/c15-audio-engine/tcd_decoder.h
- Make parameter info type safe
- Rename PARAM_XYZ_TYPES::XYZ_FOO into Xyz::Foo to have less clutter and improve readability
> Code quality only. This patch should not change programs behavior in any way.

- audio-engine/src/synth/c15-audio-engine/dsp_host.cpp
- audio-engine/src/synth/c15-audio-engine/pe_defines_config.h
- glitchy pitch issues seem fixed now
- simpler event logic for key events , avoided (most) redundant calculations (less cpu spike intensity is expected)
- fix is implemented via #define and can be disabled
- a similar fix will follow soon for the master branch (but because of large structural differences between master and dsp_optimization, cherry picking will not be helpful - so the fix will be made from scratch)
> [dsp_optimization] fixed glitchy pitch behavior for key down and note shift

- audio-engine/src/io/audio/AlsaAudioOutput.cpp
- audio-engine/src/io/midi/AlsaMidiInput.cpp
when the midi device was plugged out or the LPC was restarted.
This fix throws if reading from the midi input is not possible
any longer as the device is gone.
> The midi input code ran into an endless loop

- audio-engine/src/Options.h
- audio-engine/src/synth/c15-audio-engine/dsp_host.cpp
- audio-engine/src/synth/c15-audio-engine/dsp_host.h
- audio-engine/src/synth/c15-audio-engine/pe_defines_config.h
- audio-engine/src/synth/c15-audio-engine/pe_env_engine2.cpp
- audio-engine/src/synth/c15-audio-engine/pe_env_engine2.h
- fixed recall glitch (when previous preset has long release times, unwanted sounds can appear after recalling another preset)
- release times now are influenced by fade point (which is triggered on glitch suppression)
- Options.h now gets polyphony from pe_defines_config.h (so, the maximal number of voices only needs to be set once in the pe_defines_config.h file)
> Milestone 1.5 fix env glitch

- audio-engine/src/synth/c15-audio-engine/dsp_host.cpp
- audio-engine/src/synth/c15-audio-engine/dsp_host.h
- audio-engine/src/synth/c15-audio-engine/pe_defines_config.h
In pe_definines_config.h, a new flag determines the z-delay behavior of the FX signals for the Feedback Mixer:
- disabled (0): LinuxEngine behavior up to now - one-sample z-delay on FX dry/wet
- enabled (1): R5 Prototype behavior and new default - no z-delay on FX dry/wet
> avoid z-delay for fx signals by #define

- playground/src/proxies/audio-engine/AudioEngineProxy.cpp
set cp value of mocked send reverb / send echo parameters to 1.0 as required by parameterDB
fixes #1184
> Mock Send FX Params properly

- audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
- better log capabilities in order to monitor hw sources, keys, presets (and their single/split/layer conversions) more closely
- engine now initializes splitpoint (currently constant middle key) and both voice groups (parameters and smoothers), which leads to the engine being able to produce sound for all three dual modes
> added more detailed log functionality, better (temporary) initialization

- audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
- audio-engine/src/synth/c15-audio-engine/parameter_storage.h
- audio-engine/src/synth/c15-audio-engine/voice_allocation.h
- removed change detection from recall procedures (no internal preset loading necessary on application start)
- removed lock from recall procedures (can be completely removed from nltools/message now)
- fixed hw source ranges [0 ... 16000]
- fixed split point application in voice allocation (parameter messages follow soon..)
> Rework change detection

- playground/src/parameters/Parameter.cpp
- playground/src/parameters/names/ParameterDB.cpp
- playground/src/parameters/names/ParameterDB.h
- playground/src/testing/unit-tests/parameters/ParameterNameSaneTest.cpp
replace '@VG' in parameter name, with inverted current voice group:
eg: A/B @VG -> to A/B II on VoiceGroup I Select and A/B I on selected Voicegroup II
> Add dynamic labels

- audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
Unison Detune und Mono Glide bleiben nach Recall nun modulierbar.
(Die Modulations-Ranges sind allerdings noch nicht korrekt)
> restructured recall order for unison and mono group parameters

- projects/playground/src/presets/EditBuffer.cpp
- projects/playground/src/testing/unit-tests/dual-mode-acceptance/ConvertDualToDual.cpp
check if the old type is single, only then copy the first voice group to voice group I
if not single we are converting dual to dual and the voice groups will remain untouched
> fixes #1527

- projects/audio-engine/src/synth/C15Synth.cpp
- projects/audio-engine/src/synth/c15-audio-engine/ae_poly_section.cpp
- projects/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- projects/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
- Fade From, Fade Range now are properly recalled when receiving a Layer Preset Msg
- Single/Split Preset Msg will update the Parameters themselves, but won't have any effect
- editing of the Parameters when NOT in Layer mode will also be without effect
> Audio engine implement fade params on recall

- projects/playground/src/proxies/hwui/descriptive-layouts/concrete/menu/menu-items/AnimatedGenericItem.cpp
- projects/playground/src/proxies/hwui/descriptive-layouts/concrete/menu/menu-items/AnimatedGenericItem.h
- projects/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/items/ConvertToSoundTypeItem.cpp
- projects/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/items/InitSound.cpp
@hhoegelo 
adresses #1568 
I changed implementation of animated generic item to execute the action only after the animation played, aborting the animation by eg changing focus will not execute the action. If this behaviour is wanted problems arise about open transactions and creating transactions inside the animation callback. EG: if i press convert to single and be quick about selecting a parameter the sound type is not changed. But if we wanted to execute the callback from the destructor of the animation then the open transaction from setFocusAndMode -> reset -> animation destructor will lead to an crash. This is not an trivial problem.
> 1568 - Animation Vs Action

- projects/audio-engine/src/synth/c15-audio-engine/ae_fadepoint.cpp
- projects/audio-engine/src/synth/c15-audio-engine/ae_fadepoint.h
- projects/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- projects/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
Trying to tackle and make sense of Recall-Related Bugs (see #1600):
- fadepoint: sometimes fails to recover, staying muted
- voice reset: recalling between Layer Presets with the same Unison Voices resets Envelopes nevertheless (it shouldn't)
- wrong sound: sometimes, loaded Presets seem to fail to produce the right sound (observed with Layer <--> Layer, Layer <--> Single, Single <--> Single Presets)
> tackling #1600

- projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java
close load to part on editbuffer type change that can happen if editbuffer was converted or a whole preset was loaded
> WebUI: Close Load To Part if no longer applicable

- projects/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
In the Audio Engine, the internal smoothers were not started for Part II,  when a Layer Preset arrives. This caused Unison Clusters to only work properly in one Part. This PR here fixes that and a merge yields the following todo list in our main PR #1690 :
> fix layer-sound specific param smoother issue

- projects/audio-engine/src/AudioEngineOptions.cpp
- projects/audio-engine/src/AudioEngineOptions.h
- projects/audio-engine/src/main.cpp
- projects/audio-engine/src/synth/CPUBurningSynth.cpp
- projects/audio-engine/src/synth/CPUBurningSynth.h
- projects/nltools/src/nltools/messaging/Messaging.cpp
this patch adds a CpuBurningSynth. If commandline parameter "-u N"
is used, the CpuBuringSynth will be installed instead of the C15Synth.
The synth will then create a signal of N stereo sines (= 2 x N sine
computations per sample frame). By experimenting with "-u"-parameter,
developers can measure, how buffer sizes (latency),
buffer underruns, and CPU load (CPU load can be monitored in the shell)
depend on each other.
> In order to measure the cpu load our ePC is capable to handle,

- projects/audio-engine/src/synth/c15-audio-engine/ae_potential_improvements.h
At this Point, we are confident enough to have the latest Optimizations for the AudioEngine enabled by default, reliably reducing CPU consumption significantly.
For now, all optimization features still are optional and could still be disbabled.
When thorough testing with these features for a while reveals no issues, the features will be made permanent, and the code will be cleaned up.
If a direct comparison of a particular master commit needs to be done (comparing optimizations enabled versus disabled), I suggest to branch off from the commit, and disabling the optimizations in order to generate a non-optimized comparison build. (See Usage)
> enabled ae improvements

- projects/bbbb/systemd/bbbb.service.in
fixes bug where epc starts loading banks and displays them via bbbb even though the install-update-from-usb.service yet has to run -> bbbb should start after install-update completed
@hhoegelo or was there a particular reason to remove that dependency in the first place?
> start bbbb after install update

- projects/playground/src/presets/EditBuffer.cpp
- projects/playground/src/testing/unit-tests/dual-mode-acceptance/LoadToPartShouldNotResetRecallBuffer.cpp
- projects/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadDualPresetPartIntoLayerSoundTests.cpp
- projects/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadDualPresetPartIntoSplitSoundTests.cpp
- projects/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadSingleToLayerSoundTests.cpp
- projects/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadSingleToSplitSoundTests.cpp
removed `initRecallValues` on load to part actions, and removed all consequently failing tests -> added single test case for this behavior
closes #1899
> closes #1899

- projects/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/PlayControlParameterLayouts.cpp
> fixup value hightlight in hwsource layout

- projects/text2soled/src/Commands.cpp
- move clear() call from multitext constructor to execute()
- remove default clear() before trying to parse command line when no named command was found
==>
Display is cleared only with "multitext" command and explicit "clear" command.
Now compatible with legacy behaviour
> fixed text2soled: uncontrolled clearing of the display

- projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/ChildrenOwner.java
- projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/DragProxy.java
- projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/OverlayLayout.java
- projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SplitSoundLayout.java
The sub pages of the belt are faded out, if inactive.
Faded out controls were not treated as 'invisible' by the 'recurseChildren' algorithm
employed by DragProxy. Thus, the hidden PresetBelt-Tab handled the drag event instead
of the SoundSetting-Tab.
This patch not only fixes the 'isVisible' to respect the opacity member of 'OverlayLayouts',
it also fixes the MapsLayout.recurseChilden to respect the visibility accordingly.
#1937
> issue-1937:

- projects/bbbb/src/Application.cpp
- projects/bbbb/src/Application.h
- projects/bbbb/src/FileSystemSync.cpp
- projects/bbbb/src/FileSystemSync.h
- projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankEditButtonMenu.cpp
- projects/playground/src/proxies/hwui/panel-unit/boled/setup/ExportBackupEditor.cpp
- projects/playground/src/tools/FileSystem.cpp
- projects/playground/src/xml/FileOutStream.cpp
after booting the bbb.
Now, bbb's sync is called only if there is actually a chance that
the write operations target is the usb stick.
Also, syncing is done in background thread without blocking the main
thread anymore.
> system call 'sync' hangs up to 10 seconds when called immediately

- projects/realtime-system/src/main/src/tcd/nl_tcd_adc_work.c
fixes #1980 
Ribbon Default Calibration Data
- threshold used wrong value (must use the lowest outer left edge value of all ribbons measured, not the highest)
- safety margin was not applied to default table on init.
> Ribbon Touch Threshold, fixes issue #1980

- build-tools/bbb/CMakeLists.txt
not support cleaning the target dir. Thus, old artifacts that
we want to be sure to wipe away, have to be removed in the build rule.
Otherwise, switching between branches while re-using the pre-built buildroot
in fs.ext4 will create zombies in the final builds. (#1859)
> Fixing this in a clean way is nearly impossible: buildroot just does

- projects/playground/src/parameters/UnisonVoicesParameter.cpp
- projects/playground/src/parameters/UnisonVoicesParameter.h
- projects/playground/src/presets/EditBuffer.cpp
- projects/playground/src/presets/EditBuffer.h
- projects/playground/systemd/playground.service.in
at the code I found that at least with undo of sound type
conversions, there should be issues. (Undo restores a hard coded
state, independent from what the previous sound type was).
There is a small chance that this patch maybe fixes #1978, but
as I can't reproduce it, I can not proof its fix.
> it is not easily possible to reproduce #1978, but from looking

- projects/NonMaps/src/main/java/com/nonlinearlabs/client/WebSocketConnection.java
- projects/playground/src/http/ContentManager.cpp
- projects/playground/src/http/ContentManager.h
- projects/playground/src/http/HTTPServer.cpp
the old one. It seems that sometimes the closed web sockets are able to recover
somehow, which results in a set of web sockets, one for each broken connection.
The web sockets have all been processed leading to 'ghost moves' of knobs and faders.
Now, each webUI instance uses a random id to connect to playuground, playground only
uses exactly one web socket per client id.
> WebUI created a new web-socket whenever the connection broke and closed

- build-tools/create-c15-update/Installer_Error_Codes.txt
- build-tools/create-c15-update/update_scripts/epc_fix.sh
- build-tools/create-c15-update/update_scripts/epc_pull_update.sh
- build-tools/create-c15-update/update_scripts/epc_push_update.sh
- build-tools/create-c15-update/update_scripts/run.sh
Apparently /dev/sda4 is not always properly installed on the ePC. (I have not yet found out why). Coming from 1.5 to 1.7 this can be crucial, since /persistent is not always mounted and we cannot transfer data from the BBB.
Worked manually, have to check in context of an update on Monday.
> added sda4 fix if broken

- projects/playground/src/presets/PresetManager.cpp
editing a parameter and immediately load to part will cause the edited parameter to reset after one undo press
> fixes undo problems with load to part + direct load

- projects/playground/resources/templates/sound/select/single/SingleSoundLayout_A.json
> fix missing u and m indicators after sound name and pixel jump w/o indication

- projects/NonMaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
- projects/playground/src/presets/PresetManager.cpp
added invalidate content manager for preset manager on restore happened, and prevent only editbuffer model from update on emit oracles
> hotfix bank delete + undo / import + undo

- projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/DragProxy.java
- projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/PresetBeltButton.java
- projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/SoundBeltButton.java
added drag handler for belt preset/sound button -> enables opening / switching to belt preset/sound tab for dropping into that list / loading to part
fixes #2068
> rework preset drag behavior and add open tab behavior on preset drag

- projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/EmptyBankLabel.cpp
- projects/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetListContent.cpp
Before: 
](https://user-images.githubusercontent.com/15381257/89285358-7d87c900-d650-11ea-9ee9-ac5bff828fd9.png)
With this PR: 
](https://user-images.githubusercontent.com/15381257/89285381-87113100-d650-11ea-8fae-88b609ecf398.png)
> fix empty bank label alignment

- projects/playground/src/proxies/hwui/base-unit/LowerRibbon.cpp
- projects/playground/src/proxies/hwui/base-unit/LowerRibbon.h
The parameter is always the same so we don't need to connect to
edit buffers selection actually.
> Simplify lower ribbon to parameter connection

- projects/NonMaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
moved overlay update out from omitOracles, and fixup device info update by checking for emptyness -> no more lost infos on update
closes #2173
> issue 2173

- projects/epc/playground/src/parameters/Parameter.cpp
- projects/epc/playground/src/presets/EditBuffer.cpp
- projects/epc/playground/src/proxies/hwui/OLEDProxy.cpp
- projects/epc/playground/src/proxies/hwui/OLEDProxy.h
- projects/epc/playground/src/proxies/hwui/controls/Slider.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnit.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/BOLED.h
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MCSelectButton.cpp
with the introduction of an delayed job to install the layout, subsequent checks for layout type after `setFocusAndMode`, `undoableSelectParameter` and similar have to be passed into `onLayoutInstalled`, as upon returning of `setFocusAndMode` the layout must not be installed yet
> Issue 2198

- projects/epc/audio-engine/src/synth/c15-audio-engine/ae_poly_out_mix.cpp
fixes #2206
final mono HP of Output Mixer is now effective
Test Presets now sound okay to me.
> Hotfix #2206

- projects/epc/playground/src/presets/recall/RecallParameterGroups.cpp
- projects/epc/playground/src/serialization/RecallEditBufferSerializer.cpp
change recall parameter set xml tag to recall-param-v2 to prevent reading invalid IDS in old versions
> Fix XML to not crash on older versions

- projects/epc/playground/src/device-settings/ScreenSaverTimeoutSetting.cpp
- projects/epc/playground/src/device-settings/ScreenSaverTimeoutSetting.h
- projects/epc/playground/src/proxies/hwui/base-unit/soled/SOLEDScreenSaver.cpp
- projects/epc/playground/src/proxies/hwui/base-unit/soled/SOLEDScreenSaver.h
- projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnit.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnit.h
- projects/epc/playground/src/proxies/hwui/panel-unit/ScreenSaverUsageMode.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/ScreenSaverUsageMode.h
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/BOLEDScreenSaver.cpp
- projects/epc/playground/src/proxies/playcontroller/PlaycontrollerProxy.cpp
- projects/epc/playground/src/proxies/playcontroller/PlaycontrollerProxy.h
Fixup following ticket: #2210
and address some of the issues from #2031, but not ignoring WebUI actions which affect the Editbuffer or PresetManager.
- last pressed Key is also now consumed and ends screensaver
> Issue 2031 revisited

- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
A minor "addendum" for the AudioEngine:
Should be benefitial for future developments.
> AudioEngine - Monitor Raw MIDI

- projects/epc/playground/src/testing/unit-tests/messaging/MessagingTests.cpp
- projects/shared/nltools/include/nltools/threading/ContextBoundMessageQueue.h
- projects/shared/nltools/src/nltools/threading/ContextBoundMessageQueue.cpp
so it can happen, that the callback finally uses dangeling objects.
To fix this, we want to be sure that there are at least 2 owners of
the job when it is going to be executed: The closure and the queue.
> The jobs are scheduled to a MainContext of 'unknown' lifetime,

- projects/bbb/midi-over-ip/src/MidiOverIP.cpp
- projects/epc/audio-engine/src/synth/C15Synth.cpp
- projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp
- projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.h
- projects/shared/nltools/include/nltools/messaging/Message.h
- projects/shared/nltools/include/nltools/messaging/Messaging.h
dispatch it to midi-over-ip and the other way around
Sorry, I can't test the feature as my Roland FP-30 does not send or receive program changes.
> playground will send program changes to audio-engine, which will

- projects/epc/audio-engine/src/synth/C15Synth.cpp
- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
- projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp
> midi-over-ip ammendments

- projects/epc/audio-engine/src/synth/c15-audio-engine/ae_poly_section.cpp
Refers to: https://github.com/nonlinear-labs-dev/C15/issues/2250#issuecomment-723461077
Fixes testable with attached Bank:
solved: glide now immediately effective (similar to envelopes)
[Comb Delay Smoother Tests.zip](https://github.com/nonlinear-labs-dev/C15/files/5523605/Comb.Delay.Smoother.Tests.zip)
> AudioEngine - Comb DelaySmoother Fixes

- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
Had to remove an assertion for 7-Bit decoding: an out-of-range MIDI message shouldn't be possible anyway.
Now, this _really_ is tested numerically and runs in debug mode.
> AudioEngine - final assertion fix

- projects/bbb/bridge/src/FileSystemSync.cpp
- projects/epc/audio-engine/src/io/audio/AlsaAudioOutput.cpp
- projects/epc/audio-engine/src/io/midi/AlsaMidiInput.cpp
- projects/epc/audio-engine/src/synth/C15Synth.cpp
- projects/epc/audio-engine/src/synth/C15Synth.h
Using idle callback to send updated hw sources to playground
was a bad idea: a whole core is eaten up for this job now.
So I reused the dedicated background thread for syncing
external midi to do the playground syncing, too.
> Use event driven callback for syncing hw sources to playground

- projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java
- projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/pointer/PointerState.java
Had to remove a dangling reference from the Pointerstate. EG: If the (left drag) gesture is canceled, logically, using ESC, and then the left mouse button is released the drop action of the, gone from the overlay, dragproxy was still fired as the dragproxy lived inside the PointerState.
> closes #2299

- build-tools/CMakeLists.txt
- build-tools/create-c15-update/Installer_Error_Codes.txt
- build-tools/create-c15-update/create-c15-update.sh
- build-tools/create-c15-update/update_scripts/run.sh
- build-tools/epc2/host-os/Dockerfile
So, both ePC updates are deployed into the C15-update.tar
Then we check the kernel version and link to the corresponding ePC update within the run.sh.
tested both, seems to work fine for both ePCs
!!!***************************************!!!
https://github.com/nonlinear-labs-dev/C15/blob/epc2/build-tools/epc2/host-os/Dockerfile
is adjusted to personal needs, since my Docker Version is out of date
> Epc2 update intergration

- projects/epc/audio-engine/src/synth/c15-audio-engine/voice_allocation.h
When using overlapping Split Points, the VoiceAllocation had some issues associating different Mono und Unison settings in the different Parts ("Notenhänger"). Now, it should be possible to:
- play overlapping keys without issues, regardless of different Mono/Unison settings per part
- play overlapping keys, even if all voices in a part are exhausted (note steal) without issues
- play overlapping and non-overlapping keys simultaneously, even if all voices in a part are exhausted (note steal) without issue
A thorough Test of overlapping Split Points is necessary, of course.
> AudioEngine - integration of Overlapping Split Points

- build-tools/create-c15-update/update_scripts/run.sh
Respect operator precedence in error handling.
> Remove existing link in order to not fail following "ln -s".

- projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/BeltFadeEditorLayout.java
@MatthiasSeeber i fixed the issue you raised me: no ticket for it but i hope you remember which bug this was if not its this:
load dual preset and select preset / parameter tab, load single preset through world / boled -> webui belt tab got sound focus.
> Fixes: sound-tab opens on single preset load (if previous loaded preset was dual)

- projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/ValueEdit.java
changed doubleClick handler to be ignored, previously continously clicking on the change arrow lead to random jumps over values, as click was called from double click, this is now fixed and you can spam-click the changed arrows as much as you like without missing value steps
> WebUI: Value Edit Bug Fix

- projects/epc/playground/src/presets/BankActions.cpp
- projects/epc/playground/src/presets/PresetManager.cpp
- projects/epc/playground/src/proxies/hwui/HWUI.h
- projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/ServerProxy.java
- projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/dataModel/editBuffer/EditBufferModelUpdater.java
- projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/FadeEditorPresenterProvider.java
- projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java
- projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/maps/presets/bank/PresetList.java
HOTFIX! When Direct Load was active the select action from the WebUI was being processed deferred and then HWUI aspects have been taken into account: Load to Part Active? Yes -> load preset part to part, even if load to part in the WebUI was off. Now if direct load is on the select action will directly trigger an load. This will in turn close the Load To Part overlay that is being used in the async callback that is scheduled from selectPreset.
@hhoegelo lets talk about this
> Issue 2393

- projects/epc/playground/src/presets/EditBufferActions.cpp
This fixes #2414 which is only present if Sync Parts Across UIs is enabled.
> fixed #2414

- build-tools/bbb/CMakeLists.txt
- build-tools/bbb/Dockerfile
- build-tools/epc/Dockerfile
- build-tools/playcontroller/Dockerfile
- switch to new nonlinux version which has nlimagemaker for rescue usb sticks
@All: I had to remove the build-tools/bbb folder in my build directory after applying that fix.
@schlenkibus I will add another PR for staging, without the nonlinux update
> - Fix build problems by bumping to ubuntu 20.04 (LTS)

- projects/bbb/midi-over-ip/src/MidiOverIP.cpp
move break to outer scope, so that ignored messages also break the read loop and return to polling
> fix midi over IP CPU load on sysex and unsupported incoming messages

- projects/bbb/midi-over-ip/src/IO.cpp
- projects/bbb/midi-over-ip/src/IO.h
- projects/bbb/midi-over-ip/systemd/midi-over-ip.service.in
- projects/shared/nltools/include/nltools/logging/Log.h
fixes #2462
- Increased size of raw_midi receive buffer, buffer overflows are handled and reported, as is buffer headroom.
- Restructured receive loop. Input is now processed in blocks, not single bytes at a time. This applies both to primary (byte stream) and secondary (midi event) buffers, the latter being asynchronous with the main buffer filling loop.
- fixed memory leaks from allocating new parsers all the time, it seems ;-)
---
The reason why the previous code broke with large sysex is that it did not always consume *all* bytes in raw_midi's "I/O-ringbuffer" before the next poll() was issued. By this, raw_midi's buffer had to overflow.
---
Seems to work pretty OK by now.
Even when continuously blasted with lots of data (256kB of SysEx at a fast repeat rate while sending 20 …
> fix overrun from large SysEx data

- build-tools/epc2/create-update/createEPC2UpdateDockerCommands.sh
the system, conversions from Glib::ustrings containing
multi-byte utf-8 characters (like our MacroControl names)
to std::strings will throw.
> If there is no utf-8 enabled locale installed to

- build-tools/epc2/create-update/createEPC2UpdateDockerCommands.sh
This deploys a config file for the Networkmanager to read from and enables the latter. For now the SSID is fixed and cannot be changed. It is enough to start testing the functionality though.
> Enable Wifi on ePC2

- projects/epc/CMakeLists.txt
- projects/epc/acceptance-tests/src/Midi.cpp
- projects/epc/playground/src/testing/unit-tests/EditBufferTests.cpp
- projects/epc/playground/src/testing/unit-tests/HWUI/RibbonTests.cpp
- projects/epc/playground/src/testing/unit-tests/HWUI/TextSplitterTests.cpp
- projects/epc/playground/src/testing/unit-tests/LPC/MessageParserTests.cpp
- projects/epc/playground/src/testing/unit-tests/async/SpawnAsyncCommandLineTests.cpp
- projects/epc/playground/src/testing/unit-tests/data/IntrusiveListTests.cpp
- projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadDualPresetPartIntoLayerSoundTests.cpp
- projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadDualPresetPartIntoSplitSoundTests.cpp
- projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadSingleToSplitSoundTests.cpp
- projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/OverwritePreset.cpp
- projects/epc/playground/src/testing/unit-tests/parameters/LoadSinglePresetWithoutMcEandFResetsMcEAndFTests.cpp
- projects/epc/playground/src/testing/unit-tests/parameters/MonoParameterTests.cpp
- projects/epc/playground/src/testing/unit-tests/parameters/ParameterInvariantTests.cpp
- projects/epc/playground/src/testing/unit-tests/parameters/ParameterNameSaneTest.cpp
and replace all REQUIRE occurrences with CHECK inside test cases.
As a failing REQUIRE assertion quits the whole test-application, CHECK will log the failure and continue
> include acceptance tests again, 

- projects/epc/audio-engine/src/synth/c15-audio-engine/voice_allocation.h
fixes #2565 
The Bug fixed here has some specific circumstances that have to be met in order to observe it:
- Key Event Input needs to be "Singular" _(meaning the C15 Keybed or MIDI Receive with Secondary = "Common")_
- loaded Preset needs to be a Split Sound with monophonic Part II (bug not observable otherwise)
- before loading next Preset, press and hold a few keys in Part II
- while holding Keys, load polyphonic Layer or Single preset (bug observed with both), notes will disapper
- after loading, release held Keys and then play again (sometimes, just one voice will work, sometimes just two voices work - giving an overall monophonic impression)
The Voice Allocation did not correctly clear Keys associated with Part II (in the former Split Sound), so they still were considered "pressed" …
> fixup recall voice alloc reset

- projects/epc/audio-engine/src/synth/c15-audio-engine/smoother_handle.h
Example:
+-----------+-------------------+---------------------------------+
| Timepoint | User Interaction  |        AE param changes         |
+-----------+-------------------+---------------------------------+
| (I)       | Param A (0...1)   | Param A (0...1)                 |
| (II)      | Param A (1...0)   | Param A (1...0)                 |
| (III)     | UndoJump to (I)   | Param A (0...1),Param A (1...0) |
| (IV)      | UndoJump to (III) | Param A (0...1),Param A (1...0) |
+-----------+-------------------+---------------------------------+
On parameter changes, the AE used to compare the new target value with
the *current value* instead of the *old target value*.
If, as in (III) and (IV), two contradicting requests drop in quickly
enough, the AE did not trigger a new ramp to the …
> Fix 'Undo restores wrong sound'

- projects/epc/playground/src/presets/SendEditBufferScopeGuard.cpp
the member sendToAudioEngine is used in the lambdas long after
the SendEditBufferScopeGuard died.
> Fix use after free

- projects/epc/playground/src/libundo/undo/ContinuousTransaction.cpp
- projects/epc/playground/src/libundo/undo/ContinuousTransaction.h
- projects/epc/playground/src/libundo/undo/Scope.cpp
- projects/epc/playground/src/presets/EditBuffer.cpp
Subsequent preset selections should be combined into a ContinuousTransaction.
With direct load enabled, those transactions should loose their 'continueing'
state and create new undo entries each.
> Fix combining preset loads into one undo transaction

- projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp
implemented destructor for midi bank editor that disconnects the signal to onMidiBankSelectionHappened
closes #2612
> fix crash #2612

- projects/epc/playground/src/presets/EditBufferActions.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankAndPresetNumberLabel.cpp
- projects/epc/playground/src/tools/Uuid.cpp
- projects/epc/playground/src/tools/Uuid.h
- projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/presenters/PresetManagerPresenter.java
added 'restored' UUID and display 'Restored' if preset was copied from the past via recorder, closes #2637
> issue 2637

- projects/epc/playground/src/device-settings/ScreenSaverTimeoutSetting.cpp
- projects/epc/playground/src/device-settings/ScreenSaverTimeoutSetting.h
This is a set of little refactorings. Feel free to pick none, some or all of them.
In any case I suggest to unify connections to signals using sigc::mem_fun instead of lambdas, because we have crashes from time to time when lambdas are not able to disconnect automatically from its signal. (Currently, we don't have the problem at this place, because the setting outlives all of the senders, but code is copy-pasted, refactored etc, so I would like to introduce a general rule of  avoiding connecting lambdas to signals).
> little refactoring

- projects/epc/audio-engine/src/synth/C15Synth.cpp
- projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
Refactored MIDI Receive, the following Events are now exclusively bound to the Primary Channel:
- Control Change --> HW Sources
- Program Change --> Recall
Now, the Secondary Channel is only usable for Notes, when a Split Sound is loaded. Otherwise, the Secondary Channel should have no effect.
Closes #2662
> Issue 2662

- projects/epc/acceptance-tests/src/MIDIInputSpecialMappingsTests.cpp
- projects/epc/acceptance-tests/src/mock/InputEventStageTester.cpp
- projects/epc/acceptance-tests/src/mock/InputEventStageTester.h
- projects/epc/acceptance-tests/src/mock/MockDSPHosts.cpp
- projects/epc/acceptance-tests/src/mock/MockDSPHosts.h
- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
- projects/epc/audio-engine/src/synth/c15-audio-engine/voice_allocation.h
- projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
- projects/epc/audio-engine/src/synth/input/InputEventStage.h
- runs acceptance-tests and audio-engine-tests without fail
- sound check revealed bug is fixed
closes #2698
> issue 2698

- projects/epc/audio-engine/src/synth/C15Synth.cpp
- projects/epc/audio-engine/src/synth/C15Synth.h
- projects/epc/playground/src/device-settings/midi/HardwareControlEnables.cpp
- projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp
- projects/shared/nltools/include/nltools/messaging/Message.h
This issue said that no hardware source is working. I suspect that this is an configuration and communication issue rather than an software issue. 
Previously I added more granular MIDI/Local Settings for HW-Sources. They can be currently only found inside the WebUI -> Settings -> MIDI-Tab -> Very Bottom.
I unfortunately made the mistake of defaulting all enable-switches to 'off'. This prevents the changes to propagate thorough the system and it appears as if the Sources were not working. 
This PR fixes the defaults to be true. Also it changes the notifcation system in the InputEventStage to be able to notify either the Playground Sync or the Midi Sync. As I and @MatthiasSeeber  talked about 2 Weeks ago.
preview build can be found here: https://we.tl/t-XPsHETPTRE (this build is one commit …
> Issue 2722

- projects/epc/acceptance-tests/src/MIDI/Issue2798.cpp
- projects/epc/audio-engine/src/synth/C15Synth.cpp
- projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
- projects/epc/audio-engine/src/synth/input/InputEventStage.h
- projects/shared/nltools/include/nltools/messaging/Message.h
Stuck external notes should be fixed by sending CC 123 'All Notes Off' on both channels (if split is applicable) if the sending of MIDI notes is turned off
> closes #2798

- projects/epc/playground/src/presets/Bank.cpp
- projects/epc/playground/src/presets/Bank.h
- projects/epc/playground/src/use-cases/BankUseCases.cpp
added check to `BankUseCases` for `setAttribute` and `setCollapsed`, if the desired value is already set, no new transaction will be opened
>  closes #2833

- projects/epc/playground/src/use-cases/PresetManagerUseCases.cpp
Changed Progress-CB in import backup will no longer be written to the HWUI, the writing of the old manager will happen silently, closes #2884
> Import Backups will no longer display "writing" entries

- projects/epc/audio-engine/src/synth/C15Synth.cpp
- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
The Reset Detection now occurs within the C15Synth - no additional Playground-Logic is necessary. The Reset Detection handles Preset/Convert and Parameter Unison/Mono messages - so we should be prepared for all cases.
**Todo**: implement AllNotesOff messages for provided reset events in C15Synth
> C15Synth-only Reset Events

- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
- projects/epc/audio-engine/src/synth/c15-audio-engine/voice_allocation.h
- projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
- projects/epc/audio-engine/src/synth/input/InputEventStage.h
Recall Events of Single, Split and Layer Presets now act based on the old Preset Type, when Reset was detected. In Split Sounds loaded into Split Sounds, the reset is further influenced by Mono and Unison changes per part (based on the new Preset). A Reset Event will be canceled, if no corresponding keys are active.
> part-aware reset behavior

- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- projects/epc/audio-engine/src/synth/c15-audio-engine/voice_allocation.h
I spotted a flaw in the reset behavior when recalling Split Sounds.
As it turns out, the logic behind the reset detection gets rather complicated.
Here is an attempt to describe the current behavior:
1. LayerChanged: Has the Sound Type changed? (if yes: case non-split -> split, otherwise: case split -> split) (the voice allocation will reset if LayerChanfed)
2. Are keys pressed (depending on the old sound type)?
3. PolyChanged: While loading the parts: did Unison or Mono change in a part? (if yes, the voice allocation will reset for that part)
4. After loading the parameters: did the Sound Type change? (if yes: return outputResetEvent according to 2., otherwise: combine pressed keys with PolyChanged reflecting the parts)
> part aware reset behavior - addendum

- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
closes #2925 (hopefully for real now)
> recall, params - fix internal key counters

- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
Corrected internal reset behavior of the synth - which must remain independant from detection of pressed keys (only affecting output reset behavior).
closes #2937
> issue 2937 (recall voicing bug)

- projects/epc/acceptance-tests/src/mock/MockDSPHosts.cpp
- projects/epc/acceptance-tests/src/mock/MockDSPHosts.h
- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
- projects/epc/audio-engine/src/synth/c15-audio-engine/voice_allocation.h
- projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
Reworked non-local key assignments to be counted with any Sound Type.
I see potential for further cleanup (which can be discussed) and would like to verify the fix with a test build.
**"Holzhammer" Limitations**: there is no distinction between *internal* (LPC) and *external* (MIDI) keys for the key counter. Consider holding a MIDI Note and change Reset-relevant Parameters, Presets or Settings - an AllNotesOff will be observable (despite not being necessary).
fixes #2939
fixes #2831
> fix non-local key assignments

- projects/epc/playground/src/serialization/PresetManagerMetadataSerializer.cpp
- projects/epc/playground/src/serialization/PresetManagerSerializer.cpp
- projects/epc/playground/src/testing/unit-tests/issues/Issue2284.cpp
move selected bank and midi uuid attributes to presetmanager serializer instead of metadata serializer as the metadata is not exported to a backup, selected-bank-uuid was redundant anyways
closes #2284
> closes #2284

- projects/epc/playground/src/serialization/PresetManagerMetadataSerializer.cpp
added selected-bank-uuid back to metadata serializer to load selected bank on start
> closes #2984

- projects/epc/audio-engine/system/audio-engine.service.in
* remove unnecessary setting of FRAMES_PER_PERIOD to the value it has anyway
* reload snd_hda_intel driver if it exists (should do nothing on old epc)
> fix buffer underruns on epc2

- projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/PedalEditor.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/PedalEditor.h
change implementation of PedalEditor to save the PedalSetting as raw pointer instead of creating a shared_ptr from this ptr
closes #3015
> closes #3015

- build-tools/epc2/create-update/createUpdate.sh
- projects/epc/playground/src/playground-helpers.cpp
The macro controls names use utf-8 encoded characters for
(A)... (E). The epc2 os so far only supported ascii encoding,
thus any string function processing macro control names
failed.
This patch will not only add proper utf-8 support to the OS, but
also make the playground crash immediately if en_US.UTF-8 support
is not found on the system.
> issue #3054: Add utf-8 capable locale to epc2 os

- build-tools/epc2/build-rootfs/createRootFS.sh
If host keys are missing, they are generated on sshd startup.
Our boot process removes all files created during last run,
so rebooting will first remove the keys, then sshd will re-create
new ones. Clients will complain about changed keys - so better
ship keys with the rootfs.
> issue-3063: rootfs should come with host key

- projects/epc/playground/CMakeLists.txt
- projects/epc/playground/systemd/playground.service.in
- projects/epc/playground/systemd/wait-for-bbb-ssh.service
Sometimes, in particular after an update, the sshd on beagle bone takes
some time to start (maybe because of dicing a new host key?).
Any attempts to connect to the server are denied during that phase.
When epc tries to ssh-mount the USB stick connected to BBB, it only
tries once. If this try failes because sshd is not yet ready,
Epc has no access to the USB stick.
This patch adds a dependency to playground service in order to poll
the ssh service at BBB for at most 30s and then brute-force mounts
the usb stick. If mounting fails (because previous attempt already
suceeded), the error is just ignored (note the '-' sign).
> issue-3047: Fix race condition between sshd on bbb and ssh on epc

- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- projects/epc/audio-engine/src/synth/c15-audio-engine/voice_allocation.h
> Note Reset enhancements

- projects/epc/playground/src/presets/PresetDualParameterGroups.cpp
- projects/epc/playground/src/presets/PresetDualParameterGroups.h
- projects/epc/playground/src/presets/PresetParameter.cpp
- projects/epc/playground/src/presets/PresetParameter.h
- projects/epc/playground/src/presets/PresetParameterGroup.cpp
- projects/epc/playground/src/presets/PresetParameterGroup.h
- projects/epc/playground/src/testing/unit-tests/presets/PresetUndoTests.cpp
The copyFrom methods in preset parameter groups did not
restore parameter values on undo. Attribuites and meta data
of presets have been unrolled, while parameter values have not,
yielding frankensteins moster-presets.
(Here we have our first PR pointing to 'main' - meaning: should be part of next milestone)
> issue-3117: Fix undo when Overwriting presets

- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.java
moved setting label text to uploading.. only if we really are uploading, and remove last uploaded file after completion, so pressing cancel after succesfull upload will not pretend it has an file selected
closes #3120
> WebUI: Issue 3120: upload-firmware cancel-behaviour 

- projects/bbb/midi-over-ip/src/IO.cpp
> issue 3171

- projects/epc/playground/src/device-settings/SettingsActions.cpp
- projects/epc/playground/src/device-settings/midi/RoutingSettings.cpp
- projects/epc/playground/src/device-settings/midi/RoutingSettings.h
added sanitize to all set-ops for RoutingSetting, to prevent ReceiveSplit and ReceivePrimary not to be enabled at the same time for all entrys exept notes, those are allowed, closes #2836
> issue 2836

- projects/epc/playground/src/groups/CombFilterGroup.cpp
- projects/epc/playground/src/groups/OscillatorAGroup.cpp
- projects/epc/playground/src/groups/OscillatorBGroup.cpp
- projects/epc/playground/src/groups/SVFilterGroup.cpp
- projects/epc/playground/src/parameters/scale-converters/FineBipolar160StScaleConverter.cpp
- projects/epc/playground/src/parameters/scale-converters/FineBipolar160StScaleConverter.h
- projects/epc/playground/src/parameters/scale-converters/FineBipolar200StScaleConverter.cpp
- projects/epc/playground/src/parameters/scale-converters/FineBipolar200StScaleConverter.h
changed following scale-converters for mc-amounts:
OSC A/B:
Osc_X_Pitch_Env_C -> FineBipolar160StScaleConverter
Osc_X_PM_Self_Shp -> LinearBipolar200PercentScaleConverter
Osc_X_PM_X_Shp -> LinearBipolar200PercentScaleConverter
Comb:
Pitch Env C -> FineBipolar160StScaleConverter
Hi Cut Env C -> FineBipolar200StScaleConverter
Allpass Env C -> FineBipolar160StScaleConverter
SVF:
Resonance Env C -> LinearBipolar200PercentScaleConverter
Cutoff Env C -> FineBipolar200StScaleConverter
SV_Flt_Par -> LinearBipolar200PercentScaleConverter
@MatthiasSeeber Do we need to change the ParameterList.ods ?
closes #3221
> added FineBipolar160StScaleConverter and FineBipolar200StScaleConverters

- projects/epc/playground/src/presets/StoreModeData.h
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetListSelectStorePosition.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetListSelectStorePosition.h
fix up store-preset-list to not wrap on first bank and DEC event, but rather stay at the current selection. had to change indices to signed int instead of size_t for sanitize to work, closes #3069
> issue 3069 (store mode bank wrap)

- projects/epc/playground/src/parameters/ParameterImportConversions.cpp
added missing scale-offset conversion rules that have been forgotten in may, but since we didn't release any proper version the only problems occurred within the company and sounds created between may and now where offsets are != 0 should be reviewed
> add missing scale-offset conversion rules

- projects/epc/playground/src/device-settings/SyncSplitSettingUseCases.cpp
- projects/epc/playground/src/parameters/SplitPointParameter.cpp
- projects/epc/playground/src/parameters/SplitPointParameter.h
- projects/epc/playground/src/testing/unit-tests/parameters/SplitPointTests.cpp
- projects/epc/playground/src/use-cases/EditBufferUseCases.cpp
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/BeltParameterLayout.java
removed safety-guards for modulateable split-point, can now be modulated freely if the points are not synced. upon resyncing them, if SplitI was modulated the aspects are copied to SPII and vice versa. Also fixes Value Display bugs in ParameterBelt Modulation Aspects Focus, for unlinked splitpoints, closes #3268
> Individual modulation of Split-Point-Parameters

- projects/epc/playground/src/parameters/Parameter.cpp
- projects/epc/playground/src/presets/EditBuffer.cpp
- projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/GlobalEventSinkBroker.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ModulateableParameterLayouts.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.h
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankButton.cpp
- projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Conversion/ConvertDualToDualSoundTests.cpp
- projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadDualPresetPartIntoLayerSoundTests.cpp
- projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadDualPresetPartIntoSplitSoundTests.cpp
- projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadSingleToLayerSoundTests.cpp
- projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadSingleToSplitSoundTests.cpp
- projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/PartOriginAttributeTests.cpp
- projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/UnselectDiabledParameterOnSoundTypeChange.cpp
- projects/epc/playground/src/testing/unit-tests/issues/Issue2045.cpp
- projects/epc/playground/src/testing/unit-tests/mock/EditBufferNamedLogicalParts.h
- projects/epc/playground/src/use-cases/ParameterUseCases.cpp
- projects/epc/playground/src/use-cases/VoiceGroupAndLoadToPartManager.cpp
- projects/epc/playground/src/use-cases/VoiceGroupAndLoadToPartManager.h
- projects/epc/playground/src/use-cases/VoiceGroupUseCases.cpp
- projects/epc/playground/src/use-cases/VoiceGroupUseCases.h
added VoiceGroupUseCases, which make VoiceGroup undoable, change ParameterUseCases to include VoiceGroup in parameter-transactions, if applicable (when we are dual and the parameter is not global)
closes #2045
> issue 2045 - undo part selection

- projects/epc/audio-engine/src/recorder/Recorder.cpp
- projects/epc/audio-engine/src/recorder/Recorder.h
- projects/epc/audio-engine/src/recorder/RecorderOutput.cpp
- projects/epc/audio-engine/src/recorder/RecorderOutput.h
- projects/epc/playground/src/Application.cpp
- projects/epc/playground/src/Application.h
- projects/epc/playground/src/device-settings/SettingsActions.cpp
- projects/epc/playground/src/proxies/hwui/HWUI.cpp
- projects/epc/playground/src/proxies/hwui/HWUI.h
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/recorder/DoYouWantToStopRecorderLayout.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/recorder/DoYouWantToStopRecorderLayout.h
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/recorder/DoYouWantToStopRecorderPlaybackLayout.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/recorder/DoYouWantToStopRecorderPlaybackLayout.h
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/SetupLayout.cpp
- projects/epc/playground/src/use-cases/RecorderManager.cpp
- projects/epc/playground/src/use-cases/RecorderManager.h
- projects/shared/nltools/include/nltools/messaging/Message.h
- projects/shared/nltools/include/nltools/messaging/Messaging.h
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/useCases/SystemSettings.java
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.java
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml
added overlay which will be prompted to the user under following conditions: the last recorder connection has been closed (closing the lid on an Laptop or exiting the browser or tab) and the recorder is replaying some audio. The prompt will ask the user whether or not he wants to stop the playback of the recorder, alternatively you can now stop the playback via the HWUI and WebUI Settings, closes #2608
> issue 2608: Stop Playback of Recorder on last WebUI close

- projects/bbb/bridge/systemd/install-update-from-epc.service.in
https://github.com/nonlinear-labs-dev/C15/blob/42944b91c3bdcd5198797745eda55ba92ebcaa35/projects/bbb/bridge/systemd/install-update-from-epc.service.in
this file does not exists on the current 'main' but it was re-added with the merge of pi4 into milestone-maintance
> remove service re-added by pi4-merge

- projects/shared/configuration/lib/build.ts
- projects/shared/nltools-2/include/PresetMessages.h
> nltools-2: better enum usage

- projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp
- projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.h
- projects/epc/playground/src/use-cases/EditBufferStorePreparation.cpp
, introduced freeze/thaw-PresetMessage to prevent the intermittent EditBuffer that is modified while storing to not be send to the AE, to prevent glitches and possible stolen notes (through modulation ending envelopes for example)
> closes #3386

- projects/epc/playground/src/groups/ParameterGroup.cpp
- projects/epc/playground/src/groups/ParameterGroup.h
- projects/epc/playground/src/parameters/HardwareSourceSendParameter.cpp
- projects/epc/playground/src/parameters/HardwareSourceSendParameter.h
- projects/epc/playground/src/parameters/MacroControlParameter.cpp
- projects/epc/playground/src/parameters/MacroControlParameter.h
- projects/epc/playground/src/parameters/ModulateableParameter.cpp
- projects/epc/playground/src/parameters/ModulateableParameter.h
- projects/epc/playground/src/parameters/ModulationRoutingParameter.cpp
- projects/epc/playground/src/parameters/ModulationRoutingParameter.h
- projects/epc/playground/src/parameters/Parameter.cpp
- projects/epc/playground/src/parameters/Parameter.h
- projects/epc/playground/src/parameters/PhysicalControlParameter.cpp
- projects/epc/playground/src/parameters/PhysicalControlParameter.h
- projects/epc/playground/src/presets/EditBuffer.cpp
- projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.cpp
- projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.h
- projects/epc/playground/src/testing/unit-tests/PresetMessageTests.cpp
- projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/Loading/LoadDualPresetPartIntoLayerSoundTests.cpp
- projects/epc/playground/src/testing/unit-tests/messaging/MessagingTests.cpp
- projects/shared/nltools-2/include/PresetMessages.h
> implement fill Preset-Messages from Playground and send new Parameter-Messages 

- build-tools/pacman/c15/CMakeLists.txt
- build-tools/pacman/c15/Dockerfile.in
Mac os devices (>= Monterey) cannot connect to C15 running wpa_supplicant >= 2.10. So we have to downgrade to 2.9 which seems to work fine.
While working on this, I found that I have to pin arch updates to a dedicated version (2022-04-24) as otherwise due to the rolling distribution nature of arch linux each rebuilding of the docker container will fetch the newest version of everything.
Probably, this pinning will introduce the known 'signature' errors in the future, which I will solve then. (It is hard to fix/test it now, as currently the errors do not yet exist)
> issue-3392: Downgrade wpa_supplicant

- build-tools/pacman/c15/dockerized-create-c15-rootfs.sh
- projects/shared/version.h
there were revoked certificates that could not be approved, so installation of packages turned into a noop.
We don't need to approve package maintainers keys, so lets configure pacman accordingly.
> fix installation of c15 packages

- projects/epc/playground/src/parameters/ParameterImportConversions.cpp
- projects/shared/nltools-2/include/PresetMessages.h
Some Parameters just were refactored from being unipolar into being bipolar, their range was otherwise not affected. Those Parameters had wrong Import Conversions (0.5 * cp) which were removed. 
[Playground-Test](https://github.com/nonlinear-labs-dev/C15/files/10166461/2995-ae-playground-test.txt) and [Acceptance-Tests](https://github.com/nonlinear-labs-dev/C15/files/10166467/2995-ae-acceptance-tests.txt) yielded no fails related to this.
Unison Detune/Phase/Pan and Mono Glide were recalled with initial values due to bug in `nltools-2/PresetMessages.h::guaranteeEqualVoicesParameters` _(copied II --> I instead of I --> II)_
> fixes for 2920, 2921 and 2995

- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.h
implemented cross for 'unused' or 'disabled' FX-Parts for Single-Sounds, closes #3465
> FX-Indicator Cross for non-active FX-Parts in Single-Sound

- projects/epc/playground/resources/templates/init-screen/init-screen.json
- projects/epc/playground/src/proxies/hwui/HWUIEnums.h
- projects/epc/playground/src/proxies/hwui/descriptive-layouts/TemplateEnums.h
- projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/GlobalEventSinkBroker.cpp
- projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/GlobalEventSourceBroker.cpp
- projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferEvents.cpp
- projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferEvents.h
- projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnitPresetMode.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnitPresetMode.h
- projects/epc/playground/src/use-cases/EditBufferUseCases.cpp
- projects/epc/playground/src/use-cases/EditBufferUseCases.h
added init-screen, can be opened via holding the default-button from sound and preset-layout, closes #3417
> add new layout for init as sound-type conversion (3417)

- projects/shared/nltools-2/include/SplitPointRounding.h
https://github.com/nonlinear-labs-dev/C15/pull/3469#discussion_r1062593723
> nitpick: we could remove the static keyword from all functions inside this namespace
Merely removing the `static` keyword causes compilation errors, as the functions' symbols are redefined in test-cases. I made them `inline` instead.
I also found a redundant division which I removed, so this PR is in fact benefitial.
> Split Point Rounding - cleanup

- projects/epc/playground/src/parameters/PhysicalControlParameter.cpp
- projects/epc/playground/src/parameters/PhysicalControlParameter.h
- projects/epc/playground/src/testing/unit-tests/issues/Issue3035/PresetRecallTests.cpp
- projects/epc/playground/src/use-cases/EditBufferStorePreparation.cpp
The 'reset' of the HW-Source, which was changed via HWUI, happens only when a new Parameter is Selected. So storing a preset without first selecting MC or any other parameter can lead to a bug where the returning-hw-source is not reset before saving.
I introduced an explicit reset, of those from-hwui-changes, before the storing the preset. 
With that change i can no longer reproduce the issue @davidm2894 explained in the ticket
closes #3310
> Issue 3310, reset HW-Source, which was changed from HWUI, before Storing a Preset

- projects/epc/playground/src/device-settings/FocusAndModeSetting.cpp
- projects/epc/playground/src/device-settings/FocusAndModeSetting.h
added restrictions on which old-modes can be installed and provided alternative foci for the suppressed states, closes #3494
> issue 3494

- projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnitParameterEditMode.cpp
connected bruteForceLED update of ParameterEditMode (SignalFlowIndication) to EditBuffer::onChange to update when a parameter is changed via for example: modulation, closes #3490
> fixup SignalFlowIndication #3490

- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MiniParameter.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterCarousel.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterCarousel.h
fixup parametercarousel to no longer crash on turn and antiTurn when no other parameters are in the carousel, closes #3495
> fixup parametercarousel crash

- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/dataModel/editBuffer/ParameterFactory.java
fixup order of monophonics -> the ids were not sorted and this lead to bugs with using binarySearch, closes #3527
> WebUI: fix Flanger VoiceGroup I/II Display

- projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnit.cpp
fix parameter assignment when mc is held down and some parameter button is pressed. In single sounds we tried to assign the mc to a parameter in VG-II even the monophonics, this lead to leds showing up but no assignment visisble. closes #3523
> fix mc assignment shortcut for VG-II focus in Single-Sounds

- projects/epc/playground/src/presets/PresetDualParameterGroups.cpp
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/CompareDialog.java
poly-parametergroups will always show part I for single-presets and single-edibuffers, even when part-II is selected in the dropdown, which will now always be displayed, the monophonic parameters are displayed for each part individually, closes #3516
> added/fixup single-sound compare

- projects/bbb/scripts/c15-unit-check.sh
- projects/epc/audio-engine/src/io/audio/AlsaAudioOutput.cpp
- projects/epc/audio-engine/src/io/audio/AlsaAudioOutput.h
- projects/epc/audio-engine/system/audio-engine.service.in
- projects/shared/version.h
when experimenting with different approaches of
using alsa, we found out that we can use a polling audio loop to drive 8 buffers of 16 frames without ever experiencing underruns on 5i3 and 11i3.
> prevent buffer underruns

- projects/epc/playground/src/proxies/hwui/descriptive-layouts/ConditionRegistry.cpp
- projects/epc/playground/src/proxies/hwui/descriptive-layouts/ConditionRegistry.h
- projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/menu/menu-items/AnimatedGenericItem.cpp
- projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/menu/menu-items/AnimatedGenericItem.h
- projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/items/ConvertToSoundTypeItem.cpp
- projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/items/CopyFX.h
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/setup/OneShotEntryTypes.h
fixup all current animated sound-edit-menu items to show the animation before closing/changing the screen, added return symbol at the end of the lines of copy FX I/II items, closes #3544
> Boled: fix animation for sound-edit convert and copy-fx entries

- projects/epc/playground/src/parameters/presenter-rules/ParameterPresenterRules.cpp
- projects/epc/playground/src/parameters/presenter-rules/ParameterPresenterRules.h
- projects/epc/playground/src/presets/PresetManagerActions.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/ServerProxy.java
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/LayerSoundLayout.java
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SplitSoundLayout.java
added check for unused fx in single-preset that will be loaded-to-part, if either FX is unused we dont open the dialog to ask which FX to load but load the used FX. Moved rules into new ParameterPresenter class to have all rules in one place, closes #3564
> WebUI: don't ask for which FX to load-to-part from single if one FX is unused

- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/SelectedParameterModAmount.cpp
added minimal width of modulation-slider indicaton to be 1 px if any mod-amt is set, closes #3572
> Boled: fix-mod balken not showing minimal mod-amounts

- projects/web/static/nonmaps/src/main/webapp/NonMaps.css
- projects/web/static/nonmaps/src/main/webapp/style.css
changed preset and bank comment texts to have the same size and color as the title and position counterparts, closes #3580
tested on linux Firefox and Chromium
> WebUI: Font-Styling

- projects/epc/playground/resources/templates/generic-controls/labels/InvertedLabel.json
- projects/epc/playground/resources/templates/sound/edit/LayerSoundEditLayout.json
- projects/epc/playground/resources/templates/sound/edit/SingleSoundEditLayout.json
- projects/epc/playground/resources/templates/sound/edit/SplitSoundEditLayout.json
- projects/epc/playground/src/proxies/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferEvents.cpp
changed text of current-vg indicator in SoundEditLayout to include Part prefix before I or II, change alignment of Edit Label to Right and add some padding, closes #3504
(please note that the crash fix is not yet included, so converting from the WebUI is advised)
> Boled: Sound-Edit-Layout minor fixups of display-texts

- projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/items/ConvertToSoundTypeItem.cpp
unlock first as we send the focusAndMode signal directly -> means the layout will get reset, therefore the animated item does not exist anymore when we resume the closure, leading to the crash
> BOLED: fix crash on convert actions

- projects/shared/nltools/src/nltools/messaging/WebSocketJsonAPI.cpp
When a websocket connection is closed between receiveMessage and the according answer, it is still added to the SyncMasters list of subscribers, even though it is not anymore in the list of connections in WebSocketJsonAPI. When SyncMaster later uses its list of weak_ptr<Connection>'s, it will effectively access the WebSocketJsonAPI::m_connections' end iterator and cause UB.
> issue-3474: Fix crash

- projects/epc/playground/src/proxies/hwui/controls/PNGControl.cpp
fixup noisy logs when loading an empty image -> when DynamicLayouts want to display an Empty Phase for example when no Feedback is active in the Sound-Layouts. Now no error is reported that the desired file is a directory. As we create an empty image object and return early. closes #3570
> PNGControls -> less noise in Playground Output

- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/SoundTypeOverlayDisplay.java
replaced usage of getPixRect to rather use getRelativePositon to be correct when we are resized. closes #3584
> fixup unused FX resize problems

- projects/web/client/nonmaps-preset-search/search.less
changed white-space to break-spaces to preserve space between first and second preset part of preset-name lengths over 10 characters. closes #3589
> Preset-Search: preserve white-spaces for long preset-names

- projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnitPresetMode.cpp
do not allow the new DefaultInit screen to be opened from the Voices-transition-layout (UIDetail::Voices), closes #3517
> don't allow Default-Screen to be opened from 'Voices-Layout'

- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/CompareDialog.java
renamed part I/II to FX I/II for preset-compare, closes #3592
> WebUI: Preset-Compare use 'FX I/II' for single-sounds in drop-down instead of 'Part I/II' 

- projects/epc/playground/src/proxies/hwui/panel-unit/boled/info/MultiLineInfoContent.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/info/MultiLineInfoContent.h
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MultiLineLabel.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/MultiLineLabel.h
gave characters more space at the last line to not cut-off the pixels below, as the MultiLineInfoContent is moved by 2 pixels downwards. this showed on lowercase y or g etc.., closes #3515
> HWUI: Preset-Info last line for Multi-Line Comment does no longer get cut-off

- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/BankInfoDialog.java
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/InfoDialog/PresetInfoWidget.java
- projects/web/static/nonmaps/src/main/webapp/NonMaps.css
added updateHeight to onKeyUpHandlers for Comment-Fields, cant use onKeyown as the content has not changed (atleast after pressing return) and inital size setting won't work so we just reschedule a new calculation 15ms in the future, closes #3597
> fixup parameter and bank comments heights

- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/oleds/Oleds.ui.xml
- projects/web/static/nonmaps/src/main/webapp/NonMaps.js.in
added new mapping for soled, map all set pixels to white to increase readability on the mirror-oled display, closes #3629
> Mirror-Oleds: map all soled pixels to white

- projects/epc/playground/src/serialization/RecallEditBufferSerializer.cpp
this will prevent the editbuffer from appearing as changed after a update which changed the parameter declarations.
now the recall-parameters will also be converted according to our importrules
closes #3401
> added conversion of recall parameter set

- projects/epc/playground/src/parameters/ModulationRoutingParameter.cpp
- projects/epc/playground/src/parameters/ModulationRoutingParameter.h
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
added overwrite of getDisplayString(double) to allow RecallParameterLayout of Mod-Routers to display the values with the same formatting
closes #3643 
now:
](https://user-images.githubusercontent.com/15381257/220380852-03476065-d787-413f-8c20-b97aaffbe279.png)
> HWUI: Recall-Screen value formatting

- projects/epc/playground/src/presets/EditBuffer.cpp
- projects/epc/playground/src/presets/EditBuffer.h
added reset of changed from HWUI sources if we select any other focus but parameters (this will leave the changed value intact for parameter-edit or -info)
closes #3500
> HWUI: reset returning HW-Sources on Focus-Change if last changed from HWUI

- projects/epc/playground/src/parameters/ParameterFactory.cpp
- projects/epc/playground/src/parameters/ParameterFactory.h
- projects/shared/configuration/lib/build.ts
- projects/shared/configuration/lib/tasks/declarations.ts
- projects/shared/configuration/src/parameter_group.h.in
---
~~~
test cases:   228 |   227 passed | 1 failed as expected
assertions: 26266 | 26265 passed | 1 failed as expected
~~~
~~~ c++
// elements of individual parameter groups
inline std::vector<PID::ParameterID> getParameterIds(const Descriptors::ParameterGroup &_group) {
switch(_group) {
case Descriptors::ParameterGroups::None:
return {};
case Descriptors::ParameterGroup::Mod_HW:
return {
PID::Pedal_1,
PID::Pedal_1_Send,
// ...
};
case Descriptors::ParameterGroup::Mod_HA:
return {
PID::Pedal_1_to_MC_A,
PID::Pedal_1_to_MC_B,
// ..
};
// ...
}
// no default necessary because every ParameterGroup entry is covered
return {}; // prevent warning
}
~~~
---
`ParameterFactory::getParameterIDs` will assert when receiving an empty vector (for `ParameterGroup::None`). If this assertion is necessary …
> Yaml rework group elements

- projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnitParameterEditMode.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/PanelUnitParameterEditMode.h
added explicit check for SHP_A/B FB_ENV_C to not indicate when the position is negative, as then the env-c is not active, closes #3656
> HWUI: fixup signal flow indication for ENV_C

- projects/epc/playground/src/presets/BankActions.cpp
- projects/epc/playground/src/use-cases/BankUseCases.cpp
- projects/epc/playground/src/use-cases/BankUseCases.h
added new use-case when overwrite is pressed in the webUI while an empty bank is selected, instead of creating a new bank and storing the preset into this bank we will store the editbuffer as a preset into the current (empty) bank, closes #3655
> WebUI: Overwrite with selected empty bank

- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/LayerSoundLayout.java
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SingleSoundLayout.java
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/SplitSoundLayout.java
use separate widths and heights for different controls instead of sibling control widths and heights, closes #3657
> WebUI: 3657 arrow cleanup

- projects/epc/playground/src/device-settings/AlsaFramesPerPeriod.cpp
- projects/epc/playground/src/device-settings/AlsaFramesPerPeriod.h
- projects/epc/playground/src/device-settings/midi/RoutingSettings.cpp
- projects/shared/configuration/src/settings.yaml
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/settings/AlsaFramesPerPeriod.java
Most of the Settings appear to be reliably defaultable now, but unfortunately there are some issues remaining _(proposed default values are marked __bold__)_:
Setup: Device Settings
Setup: GUI Settings (Web UI only) are missing
- Selection Auto Scroll? (Off, Parameter, Preset, Parameter and Preset)
- Edit Parameter? (Always, If Selected, Never)
- Show Context Menus, Preset Drag and Drop? (BooleanSettings: __On__, Off)
- Display Scaling Factor? (50%, 75%, __100%__, 125%, 150%)
- Stripe Brightness (Off, 10%, 25%, 50%)
- BitmapCache, Show Developer Options (BooleanSettings: __On__, Off)
Setup: MIDI Settings
- display problem: set all routings off, load factory defaults and observe that nothing seems to have changed, then click on a checkbox and observe that now all checkboxes are in actual …
> Issue 3663 (2)

- projects/epc/playground/src/presets/UndoableVector.h
- projects/epc/playground/src/testing/unit-tests/issues/Issue3681.cpp
hotfix crash by calling resume on a tElement which was pointing to invalid memory in UndoableVector, right after swap. fixes #3681
> Hotfix: undo deleting of bank/preset

- projects/epc/audio-engine/src/synth/C15Synth.cpp
- projects/epc/audio-engine/src/synth/C15Synth.h
- projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
- projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
- projects/epc/playground/src/parameters/MacroControlParameter.cpp
- projects/epc/playground/src/parameters/Parameter.cpp
- projects/epc/playground/src/parameters/Parameter.h
- projects/epc/playground/src/parameters/PhysicalControlParameter.cpp
- projects/epc/playground/src/parameters/RibbonParameter.cpp
- projects/epc/playground/src/parameters/RibbonParameter.h
- projects/epc/playground/src/parameters/messaging/ParameterMessageFactory.h
- projects/shared/nltools-2/include/ParameterMessages.h
- projects/shared/nltools/include/nltools/Types.h
added argument to sendParameterMessage to indicate wether or not the
event should be send via midi. this argument is always true except for the case where a ribbon is changed via the bound macro-control. then we dont want to send the value, but we have to update the latched values (but I have not yet understood why)
> Issue 3690 fix

- projects/epc/playground/src/presets/Preset.cpp
- projects/web/client/nonmaps-preset-search/search.ts
feature now works for all preset-managers, as I developed this feature i had the hashtags/properties as part of the attributes for a short while, then i removed that but did not pay attention that my local preset-manager still had those attributes. local testing suggested that the preset-search by hashtags was working, but it was only working for the old preset-manager. closes #3700
> fixup: access to hashtags now works again

- projects/epc/playground/src/clipboard/Clipboard.cpp
- projects/epc/playground/src/clipboard/Clipboard.h
- projects/epc/playground/src/use-cases/PresetManagerUseCases.cpp
add explicit member referencing the last presets uuid that was cut. (as the old behaviour of assuming the preset in the m_content will have the same uuid as the old preset) closes #3701
> hwui/webui: fix cut preset not being removed from old bank

- projects/epc/playground/src/proxies/hwui/FourStateLED.cpp
- projects/epc/playground/src/proxies/hwui/FourStateLED.h
add option to send the led state non-throttled -> only do that when we are shutting down, as the throttler would be destroyed before it has a chance to send its state, closes #3705
> fix ribbon leds not set to 100% upon shutdown

- projects/epc/audio-engine/src/synth/C15Synth.cpp
> reintroduced check for send-active-sensing setting, closes #3722

- projects/epc/audio-engine/src/synth/C15Synth.cpp
- projects/epc/audio-engine/src/synth/C15Synth.h
added boolean flag that will be set when midi-settings are received, and if we did not receive the settings from the playground yet we do not send active-sensing, closes #3728
> MIDI: only send active-sensing after midi message from PG got received

- projects/epc/playground/src/testing/unit-tests/issues/Issue2905.cpp
- projects/epc/playground/src/testing/unit-tests/issues/Issue3343.cpp
added [slow] tag to tests which take way over 20 seconds to run, when invoking the test-application we can pass this argument now: `~[slow]`  to exclude those tests from the test-run
> Unit-Tests add [slow] tag

- projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetPropertyDisplay.cpp
- projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/PresetPropertyDisplay.h
- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/InfoDialog/PresetPropertiesLabels.java
- projects/web/static/nonmaps/src/main/webapp/NonMaps.css
fixup display of preset-hashtags in webui and hwui -> do not use 25% of the total with but use flex-layout in webUI and margin in HWUI, closes #3733, closes #3710
> WebUI/HWUI: cleanup properties/hashtag displays

- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/belt/sound/FadeIndicator.java
disabled mouse-over animation states for Fade-Range symbol. closes #3784
> WebUI: fixup Fade Indicators can be 'clicked'

- projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/Parameter.java
the load state of the svg image was ignored when calculating the check sum, so CachedBitmapControl had not reason to redraw the children
> issue-1807: fix missing svg image redraws

- projects/epc/audio-engine/readme.md
> [Production Refinements] updated audio engine readme

- projects/bbb/scripts/c15-unit-check.sh
- added: ePC, check_persistent_integrity(), testing file system integrity for /dev/sda4 (mounted to /persistent)
- fixed: check_usb_stick() output formatting
- fixed: check_lpc() make sure correct data is read from lpc
- added: executeAsRoot() is silent when $1 is empty string
> c15-unit-check.sh: add /dev/sda5 (/persistent) integrity check
